uwblueprint/focus-on-nature

backend/typescript/models/camp.model.ts
backend/typescript/rest/camperRoutes.ts
backend/typescript/services/implementations/camperService.ts
backend/typescript/services/interfaces/camperService.ts

[Ticket Name](https://www.notion.so/uwblueprintexecs/Task-Board-38b49f83f6ce4b07ae188dabb37631e8?p=021b3b1505964056bbe9c30290d73a44)
* Added `camper/campers` route which allows querying for all campers or only campers that belong to a camp, if the `campId` parameter is given
1. Test manually in Postman - create a GET request to `/camper/campers` with no `campId` parameter and ensure no errors in console logs, and also that all the campers belonging to the mongoDB database are returned
2. Create a GET request to `camper/campers` with a valid, existing `campId` parameter and ensure no errors + only campers that belong to the camp are returned
3. Add in a `campId` parameter for a camp that doesn't exist and ensure that error message is returned with status 500.
* Error handling on getting …

feat: GET campers endpoint

---

backend/typescript/rest/camperRoutes.ts
backend/typescript/services/implementations/camperService.ts
backend/typescript/services/interfaces/camperService.ts

[Ticket Name](https://www.notion.so/uwblueprintexecs/Tasks-38b49f83f6ce4b07ae188dabb37631e8?p=b9d06121a6a34f27ae174e3adfed252c)
* Added `camper/:camperId` route allowing for an admin user to delete a camper by the camper ID
* This endpoint will delete the camper from the campers collection in the database and the campers field of the camper's camp
1. Similar to https://github.com/uwblueprint/focus-on-nature/pull/24 , want to test manually by creating a DELETE request to the endpoint with camper ID
2. Test multiple cases: if the camper ID doesn't exist, the camp associated with the camper doesn't exist, test if the camper deletion throws an error then should rollback, test if rollback throws an error, and test a valid camper ID.
3. Note that these cases are already tested ^
* Verifying the …

feat: delete camper by camper ID API

---

backend/typescript/services/implementations/camperService.ts

[Registration API: capacity check](https://uwblueprintexecs.notion.site/Registration-API-capacity-check-136ccc0ae90f4169a8e37351bb5ad302)
* Added camp capacity check to create camper service
1. Make a new POST request at http://localhost:5000/camper/register
2. Set the camp field to a camp that's full --> request should through an error stating "Error: camp is full" 
3. Set the camp field to a camp that's not full --> request should return request body as expected 
* Are the error messages formatted correctly? 
* Is there a more efficient way to do this?

feat: registration api capacity check

---

backend/typescript/middlewares/validators/camperValidators.ts
backend/typescript/package.json
backend/typescript/rest/camperRoutes.ts
backend/typescript/services/implementations/camperService.ts
backend/typescript/services/interfaces/camperService.ts
backend/typescript/yarn.lock

[Ticket Name](https://www.notion.so/uwblueprintexecs/Tasks-38b49f83f6ce4b07ae188dabb37631e8?p=1a6a18a0dfb24ceeabba62338e200e57)
* Added call to Stripe API to refund and delete users based on charge ID and a given list of camper IDs
* Partial refunds can be done, depending on the given camper IDs to delete and the amount paid for each camper
* Note that currently the secret key being used is the test key (test transactions), and will need to be updated when the project is deployed
1. Register a new camper so that they are added to the database, and create a test Payment Intent to the Stripe account. There is no code for this yet but you can try running this code before creating the camper, using the generated charge ID for registration:
```
const paymentIntent = await …
```

feat: issue Stripe refund when camper is deleted

---

backend/typescript/middlewares/validators/campValidators.ts
backend/typescript/models/camp.model.ts
backend/typescript/models/campSession.model.ts
backend/typescript/rest/campRoutes.ts
backend/typescript/services/implementations/__tests__/campService.test.ts
backend/typescript/services/implementations/campService.ts
backend/typescript/types.ts

[Camp model update](https://uwblueprintexecs.notion.site/Camp-model-update-b4bccf767f484ae7b2a4ec03e34f7f69)
* moved capacity field from camp to campSession 
1. make a post request at `http://localhost:5000/camp`
Sample request body: 
```
{
"ageLower": 10,
"ageUpper": 22,
"name": "hihi",
"description": "test",
"location": "canada",
"fee": 20,
"formQuestions": [
{
"id": "6229700fc097b201b8edb3e6",
"type": "Text",
"question": "question test",
"required": true,
"description": "this is the description for question test",
"options": []
}
],
"campSessions": [
{
"capacity": 42,
"dates": [
"Thu Dec 02 2021 00:00:00 GMT+0000 (Coordinated Universal Time)",
"Thu Dec 30 2021 00:00:00 GMT+0000 (Coordinated Universal Time)"
],
"startTime": "12:40",
"endTime": "16:50",
"registrations": 0,
"waitlist": 0, …
```

fix: moved capacity to campSession

---

backend/typescript/services/implementations/authService.ts

[Verify access management ](https://www.notion.so/uwblueprintexecs/Task-Board-S22-1a3e651ab8544192bf0fdcbba04f6d03?p=ab3e8dc45b3e4a56af7e7bb95405f5ef)
* Check `active` field on user if the user already exists. If `active` is false, they should not be able to sign in.
1. Test signing in with `active` as both true and false on your user account. You may have to delete local storage to be able to log out properly.
* nature! :D

fix: prevent inactive users from signing in

---

backend/typescript/models/campSession.model.ts
backend/typescript/services/implementations/camperService.ts

[Registration API - capacity check enhancement](https://uwblueprintexecs.notion.site/Registration-API-capacity-check-enhancement-8ad08840bd72465a8a9b2732c18a3487)
* moved camp capacity validation from camperService to camper.model
* this change was implemented to prevent race conditions from occurring upon registering a new camper to a camp session
1. Make a new POST request at http://localhost:5000/camper/register
2. Set the campSession field to a camp that's full --> request should through an error stating "Error: camp is full"
3. Set the campSession field to a camp that's not full --> request should return request body as expected
* Are the error messages formatted correctly?
* Is there a more efficient way to do this?

feat: add capacity check on campsession update

---

backend/typescript/rest/campRoutes.ts
backend/typescript/services/implementations/__tests__/campService.test.ts
backend/typescript/services/implementations/campService.ts
backend/typescript/services/interfaces/campService.ts

[Ticket Name](https://www.notion.so/uwblueprintexecs/Task-Board-S22-1a3e651ab8544192bf0fdcbba04f6d03?p=36046d9832f345aa824e498808614fcc)
* added delete camp endpoint which takes in a camp id and deletes the camp's form questions, file, and camp sessions
* modified camp session deletion to also delete the associated campers
1. Create a camp with an associated file, form questions, and camp sessions each with campers
2. Ensure deletion will delete all these fields from the database
3. If a camp session deletion fails, the program shouldn't throw an error in the middle of camp sessions deletions, but rather at the end
* Ensure error handling is correct for camp session deletion

feat: add delete camp endpoint

---

backend/typescript/rest/campRoutes.ts
backend/typescript/services/implementations/campService.ts
backend/typescript/services/interfaces/campService.ts

[Get Camp by camp id](https://www.notion.so/uwblueprintexecs/Get-Camp-by-camp-id-a2d958a9e0de4f60bc3c47dd5a5968db)
* added a getCampById end point to retrieve a camp by its Id 
1. send a get request at `http://localhost:5000/camp/:id` 
* does the endpoint return all requested information?

feat: get camp by camp id

---

frontend/src/components/common/NavBar.tsx

Bug Fix
* Centered columns by having left and right fill space (https://stackoverflow.com/questions/29503227/how-to-make-flexbox-items-the-same-size)
* Centered the tabs using isFitted property
1. Visual test, verify for small screen widths
2. Test for long names
* Not sure about cases where not all the tabs are shown

Fix: Fix Navbar Centering

---

backend/typescript/rest/camperRoutes.ts
backend/typescript/services/implementations/camperService.ts
backend/typescript/services/interfaces/camperService.ts

[Ticket Name](https://www.notion.so/uwblueprintexecs/Waitlist-Update-status-of-waitlisted-camper-who-registers-4e33b329a79f41749509158c745e39ec)
* Added check to ensure only one camper is being updated and then updated the field on waitlisted camper
1. ensure endpoint works as expected and changes a waitlisted camper put into query params
* Right now, we are making createCampers work as an endpoint that returns multiple campers. However, we can only change one waitlisted camper at a time since there is no other way to relate a waitlisted camper to their information without it getting unnecessarily complex. As such, should this be abstracted out into another endpoint that would only create one camper (would call createCampers function but only feed one camper) and all the waitlistedCamper …

Feat: Update Waitlisted Camper to "Registered" after Camper is Created

---

backend/typescript/services/implementations/campService.ts
backend/typescript/types.ts

[Camp Overview Photo](https://www.notion.so/uwblueprintexecs/Camp-Overview-Camp-Photos-3c56402473f646c4a6b985a9925969ea)
* Returning a link to the camp photo in the get camps endpoint in the `campPhotoUrl` field
1. Make GET requests to http://localhost:5000/camp/
2. Check that the correct link is returned.
*

feat: return camp photo link in get camp endpoint

---

frontend/src/APIClients/UserAPIClient.ts
frontend/src/components/pages/AccessControl/index.tsx
frontend/src/types/UserTypes.ts

[Access Management: Change User Role](https://www.notion.so/uwblueprintexecs/Access-Management-Change-User-Role-52f1f83dcba04aa6a27400298ba900f8)
* Add functionality to change a user's role from FON Admin -> Camp Coordinator and vice versa
1. Log in as an Admin and go to the Access Control table
2. Select a user to change a role in the row's dropdown
3. Upon successful change, a success toast message should appear.
4. Go to MongoDB and make sure the change is reflected in the DB
*

Feat: Implement change user role to access control table

---

frontend/src/components/pages/AccessControl/ConfirmStatusChangeModal.tsx
frontend/src/components/pages/AccessControl/index.tsx

[Access Management: Change user status](https://www.notion.so/uwblueprintexecs/Access-Management-Change-user-status-549c554ea8f14db5a7dee9ab43de28aa)
* Added onClick handler to the 3 dots symbol for each row to show a confirmation modal popup and allows user to mark a user in the table as inactive or active
1. Log in as an admin and go to the Access Control table
2. Choose a user that is active, and mark them as inactive. They should properly be updated in MongoDB and a success toast should be displayed.
3. Choose a user that is inactive, and mark them as active. This should also be updated in MongoDB and a success toast should be displayed.
4. Make sure the designs accurately match
* Coding practices
* Make sure components match designs

feat: Implement access control table change status function

---

frontend/src/components/pages/CampsList/CampsNavigationHeader.tsx
frontend/src/components/pages/CampsList/CampsNavigationHeading.tsx
frontend/src/components/pages/CampsList/index.tsx

[Camp List: Page heading + navigation](https://www.notion.so/uwblueprintexecs/Task-Board-S22-1a3e651ab8544192bf0fdcbba04f6d03?p=751be149873441978d6dda7f4ef202bd&pm=s)
* Built a component for just the heading of the Camps List, with buttons for navigation between years
1. Test out dummy page under CampsList
2. Attempt integrating with Camp List Table page
* Does the component match designs

Feat: Camp List Page Header

---

.github/workflows/lint.yml
backend/typescript/services/implementations/userService.ts
frontend/src/APIClients/UserAPIClient.ts
frontend/src/components/pages/CampOverview/index.tsx

- Currently when calling the get users endpoint, the entire request fails when one user is invalid (i.e. lookup in Firebase auth fails). Instead of failing the entire request we want to return the valid users.
- Adding some nullchecks where the UI was crashing
- Adding linting checks on dev branch
1. Remove the `authId` field on a dummy user in the db to make this user invalid (or make a new entry leaving out the `authId` field).
2. Make a GET request to /users (navigating to a camp details page when you're signed in as an admin is an easy way to do this, can use http://localhost:3000/admin/camp/63139c7bc3d7b55b44a01531). 
3. Check in the network tab that the request to /users was successful and has returned users.
*

fix: get users

---

frontend/src/components/pages/AccessControl/index.tsx
frontend/src/components/pages/CampOverview/CampersTable/WaitlistedCampersTable.tsx
frontend/src/theme/colors.ts

* Design request
-> setup one of the buttons as a demo
```ts
toast({
description:
"Registration link has been sent and they will be notified.",
status: "success",
variant: "subtle",
duration: 3000,
});
toast({
description:
"Registration link has been sent and they will be notified.",
status: "info",
variant: "subtle",
duration: 3000,
});
toast({
description:
"Registration link has been sent and they will be notified.",
status: "warning",
variant: "subtle",
duration: 3000,
});
toast({
description:
"Registration link has been sent and they will be notified.",
status: "error",
variant: "subtle",
duration: 3000,
});
```
https://user-images.githubusercontent.com/40974372/193250176-45f2445d-ea86-4abe-a402-996fe6cc17f8.mov
*

Change toast styling to subtle

---

frontend/src/components/pages/CampOverview/Footer.tsx
frontend/src/components/pages/CampOverview/index.tsx

* Presentation only - buttons don't work yet
[Camp Overview: Footer + Actions](https://www.notion.so/uwblueprintexecs/Camp-Overview-Footer-Actions-9ef2fa77aa924218b4a425ba60d37b43)
* Added footer to display buttons in Camp Overview
1. Go to unpublished camp, footer should look like this:
2. Go to published camp, footer should look like this:
* Just the conditional rendering

feat: add camp overview footer (presentation)

---

frontend/src/APIClients/CampsAPIClient.ts
frontend/src/components/pages/CampOverview/Footer.tsx
frontend/src/components/pages/CampOverview/FooterDeleteModal.tsx

[Camp Overview: Footer + Actions](https://www.notion.so/uwblueprintexecs/Camp-Overview-Footer-Actions-9ef2fa77aa924218b4a425ba60d37b43)
* Added delete action to camp overview footer
1. Create new camp
2. Go to camp overview page for said camp and use the delete flow
* I used a state to conditionally render the Redirect - let me know if there's a better way to do that.

feat: add camp overview footer (camp deletion)

---

backend/typescript/middlewares/validators/campValidators.ts
backend/typescript/rest/campRoutes.ts
backend/typescript/services/implementations/campService.ts
backend/typescript/services/interfaces/campService.ts
backend/typescript/types.ts

[Camp Overview: Delete Session + Change Session Capacity](https://www.notion.so/uwblueprintexecs/8902e20b0cae4db2b4776259238f8a4e?v=4cf916ddabfc4438a2685c0990a4fc57&p=6d18cb517d61447ab691f8a7d37978f6&pm=c)
* Note that implementation is different that `deleteCampersById`
1. Make a DELETE call with existing camp sessions
3. Make a DELETE call with non-existing camp sessions
* Nothing specific, is the approach readable and does it makes sense?
* better approach would use transactions

Create DELETE endpoint for multiple camp sessions

---

backend/typescript/rest/camperRoutes.ts
backend/typescript/services/implementations/camperService.ts
backend/typescript/services/interfaces/camperService.ts
frontend/src/APIClients/CamperAPIClient.ts
frontend/src/components/pages/CampOverview/CampDetails.tsx
frontend/src/components/pages/CampOverview/CampRegistrationLink.tsx
frontend/src/components/pages/CampOverview/CampersTable/CampersTable.tsx
frontend/src/components/pages/CampOverview/CampersTable/CampersTables.tsx
frontend/src/components/pages/CampOverview/RemoveCamperModal/ConfirmModal.tsx
frontend/src/components/pages/CampOverview/RemoveCamperModal/SelectModal.tsx
frontend/src/components/pages/CampOverview/RemoveCamperModal/index.tsx
frontend/src/components/pages/CampOverview/index.tsx
frontend/src/theme/colors.ts
frontend/src/theme/textStyles.ts
frontend/src/types/CamperTypes.ts

[Camp Overview: Remove Camper(s) from session](https://www.notion.so/uwblueprintexecs/Camp-Overview-Remove-Camper-s-from-session-9c2c0522fc6c41f9a3e34203f2d0bd65)
* Created new functions to delete campers by id and get campers that have the same specified charge id and session id, in `CamperAPIClient.ts`
* Added implementation for `getCampersByChargeIdAndSessionId` in the `CamperService.ts` files
* Created a new route for this endpoint to use
* Made the modals to interact with everything
1. Navigate to the Guelph camp for instance, http://localhost:3000/admin/camp/63139c7bc3d7b55b44a01531
2. Remove different campers, ensure it works
* Ensure that removing campers with different session ids and charge ids are seperated (i.e. in the checkbox that pops up when removing, the checkbox should …

Camp Overview: Remove Camper(s) from session

---

backend/typescript/middlewares/validators/campValidators.ts
backend/typescript/rest/campRoutes.ts
backend/typescript/services/implementations/__tests__/campService.test.ts
backend/typescript/services/implementations/campService.ts
backend/typescript/services/interfaces/campService.ts
backend/typescript/types.ts

[Camp Overview: Delete Session + Change Session Capacity ](https://www.notion.so/uwblueprintexecs/Camp-Overview-Delete-Session-Change-Session-Capacity-6d18cb517d61447ab691f8a7d37978f6)
* Create bulk update at `PATCH /camp/:camp_id/session`
* Change update endpoint at `PATCH /camp/:camp_id/session/:session_id` to not make capacity and dates both mandatory
`PATCH /camp/63538bc01bf0453b8a55ea1a/session`
- tested malformed inputs (invalid primitives, non-array body)
- tested happy path, all / partial fields (example body has both)
- tested invalid id, id does not exist cases
```json
{
"updatedCampSessions": [
{
"id": "6353a97ff9b07c73611423ed",
"capacity": 22
},
{
"id": "6353b23dbd2327c976b7ee6a",
"capacity": 23, 
"dates": [
"Mon Mar 14 2022 12:00:00 GMT+0000 (Coordinated Universal Time)", …
```

Create bulk update camp sessions endpoint

---

backend/typescript/middlewares/validators/adminValidators.ts
backend/typescript/rest/adminRoutes.ts
backend/typescript/services/implementations/adminService.ts
backend/typescript/services/interfaces/adminService.ts
backend/typescript/types.ts

[Form Management: Add question to form template](https://www.notion.so/uwblueprintexecs/Task-Board-F22-9e03bf9f7c4343f09a8a5c16dc48a12a?p=872084408d3543a3ad120dcc9808a9a1&pm=c)
* just your standard endpoint changes tbh
* decided to make the body of the form `formQuestion: {...}` instead of just the fields. This was to leverage the existing `validateFormQuestion()` function more directly. 
* Decided to implement this function in the adminService as I think it does belong there. Some of the existing work for formquestions seems to be in the `campService` but I think it's better suited here. (For camp creation, I think we should add new functions like `addQuestionsToCamp` like the one I added in this PR)
1. Make a PATCH request to `http://localhost:5000/admin/formTemplate/formQuestion/` (you …

added the addQuestionToFormTemplate in the admin service

---

backend/typescript/middlewares/validators/campValidators.ts
backend/typescript/rest/campRoutes.ts
backend/typescript/services/implementations/__tests__/campService.test.ts
backend/typescript/services/implementations/campService.ts
frontend/src/APIClients/CampsAPIClient.ts
frontend/src/components/pages/CampOverview/index.tsx
frontend/src/types/CampsTypes.ts

[Camp Overview: Delete Session Change, Change Session Capacity](https://www.notion.so/uwblueprintexecs/Camp-Overview-Delete-Session-Change-Session-Capacity-6d18cb517d61447ab691f8a7d37978f6)
Outstanding pieces of UX work
1. Create sessions if needed
2. End to end flow testable -> Open "Manage Sessions" Modal, delete and/or edit capacities
3. Check that modal closes, state updates as expected. If you re-open the modal, your changes should be as expected
* Check comments on PR

Connect Manage Sessions modal to API Client

---

frontend/src/components/pages/GlobalForms/WaiverTab/DeleteWaiverModal.tsx
frontend/src/components/pages/GlobalForms/WaiverTab/EditWaiverModal.tsx
frontend/src/components/pages/GlobalForms/WaiverTab/WaiverSectionCard.tsx
frontend/src/components/pages/GlobalForms/WaiverTab/index.tsx
frontend/src/components/pages/GlobalForms/index.tsx

[Edit + Delete Front end ](https://www.notion.so/uwblueprintexecs/Task-Board-F22-9e03bf9f7c4343f09a8a5c16dc48a12a?p=b4dbb43b89144b8f8b4d54ba04725a0e&pm=c)
* I added two modals for the edit and delete confirmation in the WaiverSectionCard.ts file
* I added two functions onDeleteWaiverSection and onEditWaiverSection in the GlobalForms/index.ts file and passed these down so that we could call the API at the highest level instead of changing state multiple times
1. Try editing a section -> the section should change and there should be a success toast
2. Try deleting a section -> the section should disappear and there should be a success toast
* I'm not sure if I'm handling state the best way in the WaiverSectionCard.ts file, I went back and forth with splitting up the modals into multiple …

Frontend - Waiver Section Edit/Delete

---

backend/typescript/middlewares/validators/adminValidators.ts
backend/typescript/rest/adminRoutes.ts
backend/typescript/services/implementations/adminService.ts
backend/typescript/services/interfaces/adminService.ts

[Form Management: Edit/remove question in form template](https://www.notion.so/uwblueprintexecs/Task-Board-F22-9e03bf9f7c4343f09a8a5c16dc48a12a?p=792e8a8c96954713a7399446547c0fad&pm=c)
* made a new endpoint for editing a question in the form template
* made a new function in the admin service to "edit" the form question
1. Make a PATCH request to `/admin/formTemplate/formQuestion/:oldQuestionId` <-- get this form mongoDB 
2. use postman with the following body:
```
{
"newFormQuestion" : {
"category": "CampSpecific",
"type" : "MultipleChoice",
"question": "Can the camper swim?",
"required" : false,
"description" : "We will not have life guards on duty",
"options": ["Yes", "No"]
}
}
```
3. You should get `true` if the oldQuestionId you provided was in the template
4. Make sure to test error …

Edit/Remove formQuestion from formTemplate backend

---

frontend/src/components/pages/CampsList/CampsTable.tsx

Spontaneous bug fix for inifinite loop of getCamps request
* 
1. Open the camp list page and go to inspect element -> network tab 
2. Verify that the request to get all camps is not being repeatedly called
*

Fix: Removes infinite loop in getCamps request on Camp List table

---

backend/typescript/services/implementations/campService.ts
backend/typescript/services/interfaces/campService.ts
backend/typescript/types.ts
frontend/src/APIClients/CampsAPIClient.ts
frontend/src/components/pages/CampOverview/CampersTable/CampersTable.tsx
frontend/src/components/pages/CampOverview/CampersTable/CampersTables.tsx
frontend/src/components/pages/CampOverview/index.tsx
frontend/src/utils/CSVUtils.ts

[Camp Overview: Trigger CSV functionality](https://www.notion.so/uwblueprintexecs/Camp-Overview-Trigger-CSV-functionality-86ffe05420a84280a9c8bcec77606dd7)
* Added new function to CampersAPIClients to call backend API for getting CSV string corresponding to camp session ID
* Passed down camp session ID from CampersTable to CamperTable, which is then passed to export CSV button 
* When the export CSV button is clicked, the function in CampersAPIClients is called and the returned CSV string is converted and then downloaded
1. Go to http://localhost:3000/admin/camp/63139c7bc3d7b55b44a01531
2. Click the "export as .csv" button
3. CSV should download and contain content corresponding to the current camp session
* Want to ensure workflow to fetch, convert and download CSV is as efficient as …

feat: Download CSV for Camp Session

---

frontend/src/components/pages/CampOverview/CampersTable/CampersTable.tsx
frontend/src/components/pages/CampOverview/CampersTable/CampersTables.tsx
frontend/src/components/pages/CampOverview/index.tsx
frontend/src/components/pages/CampsList/CampsTable.tsx
frontend/src/components/pages/CampsList/PreviewCampDrawer.tsx
frontend/src/components/pages/CampsList/PreviewModalSessionRow.tsx
frontend/src/components/pages/CampsList/index.tsx
frontend/src/utils/CSVUtils.ts

[Camp List: Camp Preview](https://www.notion.so/uwblueprintexecs/Task-Board-F22-9e03bf9f7c4343f09a8a5c16dc48a12a?p=ec49d3c3237d4080adecdc321f7df86c&pm=c)
- Implemented camp preview drawer as per designs and ticket
Design justification:
- Only clicking the name/address area of a table's row activates the drawer. If the whole row is clickable, clicking the triple dot button activates both the drawer and delete camp tooltip popup at the same time
- Changing the year closes the drawer as some years don't have camps
- Drawer is fixed right now, on the assumption that the navbar will be made sticky
1. Click on camps to open the drawer
2. Close the drawer
3. Scroll and see if the drawer stays fixed (there will be a gap at the top as the navbar is not sticky in my branch but from Slack …

Create camp list preview drawer

---

frontend/src/APIClients/AdminAPIClient.ts
frontend/src/APIClients/CamperAPIClient.ts
frontend/src/APIClients/CampsAPIClient.ts
frontend/src/APIClients/UserAPIClient.ts
frontend/src/components/pages/CampCreation/index.tsx
frontend/src/constants/AuthConstants.ts

[Access management table not loading on first visit](https://www.notion.so/uwblueprintexecs/Access-Management-Table-not-loading-on-first-visit-0ccaa7ab18504bb787071999442079c9)
* The access management table was not loading on first load because the BEARER_TOKEN was `null` for some reason, we found that changing the `BEARER_TOKEN` constant to be a function fixed the issue, probably bc when the `BEARER_TOKEN` first gets its value upon page load, it doesn't update unless we refresh the page, but we want to get the access token value at the given moment
1. Login
2. Go to access management page for the first time upon logging in
3. Data in the table should load without refreshing
*

fix: Replace BEARER_TOKEN constant to be a function

---

frontend/src/APIClients/BaseAPIClient.ts

[Login Auth not working after token expires](https://www.notion.so/uwblueprintexecs/Login-Auth-refresh-not-working-after-token-expires-7e98633addd04560a6ffeb028d3a0fdc)
* Auto log out user instead of doing the refresh (see the Community Fridge fix for the same issue: https://github.com/uwblueprint/community-fridge-kw/pull/193)
1. Log in
2. After 1 hour, you should automatically be logged out
*

fix: Auto log-out user instead of refreshing when token expires

---

frontend/src/components/common/formQuestions/AddQuestionModal/index.tsx
frontend/src/components/pages/GlobalForms/Footer/Footer.tsx

[Global Forms: Remove the “Camp Specific” option if the admin is trying to add a question to the global forms](https://www.notion.so/uwblueprintexecs/8902e20b0cae4db2b4776259238f8a4e?v=4cf916ddabfc4438a2685c0990a4fc57&p=5067a23b7d1e4fc4b58d7f10cf195484&pm=c)
* 
1. try to add a question on camp creation flow and to the form template
*

removes the Camp Specific option from form template add question modal

---

.github/workflows/heroku-deploy-dev-ts.yml

https://devcenter.heroku.com/articles/git#deploy-from-a-branch-besides-main
https://help.heroku.com/CKVOUPSY/how-to-switch-deployment-method-from-github-to-heroku-git-with-all-the-changes-app-code-available-in-a-github-repo
* 
1.
*

fix: heroku only considers pushes from main branch

---

frontend/src/components/pages/CampCreation/CampDetails/index.tsx
frontend/src/components/pages/CampCreation/RegistrationForm/index.tsx
frontend/src/components/pages/CampCreation/index.tsx
frontend/src/constants/FixedQuestions.ts

[Camp Creation/Editing: Conditionally Rendering EDLP Question on Registration Form](https://www.notion.so/uwblueprintexecs/Task-Board-F22-9e03bf9f7c4343f09a8a5c16dc48a12a?p=ea914f89233f4590afbc27a11e274cf7&pm=c)
* 
1. go through the create camp flow
*

Fix: Conditionally renders EDLP question based on state from camp details page

---

frontend/src/components/pages/CampOverview/CampersTable/CampersTable.tsx

[Campers table: page crashes when secondary contact is not provided](https://www.notion.so/uwblueprintexecs/Task-Board-F22-9e03bf9f7c4343f09a8a5c16dc48a12a?p=e9a3f31a29cb47a98103a090dd69d59e&pm=c)
* 
1.
*

Fix: Supports optional secondary contact info rendering in campers table

---

frontend/src/components/pages/AccessControl/index.tsx
frontend/src/components/pages/CampsList/CampsTable.tsx

[Center-align status header on camps list table and access control table](https://www.notion.so/uwblueprintexecs/Center-align-status-header-on-camps-list-table-and-access-control-table-db6f4a2c07de4b4cb50901e8b0eb7498)
* 
1. go to camp list table / access control table
2. check that the `Status` header is centered
*

Center-align status header on camps list table and access control table

---

frontend/src/components/pages/CampCreation/ScheduleSessions/SidePanel/CurrentSessionsView.tsx
frontend/src/components/pages/CampCreation/ScheduleSessions/SidePanel/ScheduledSessionsCard.tsx

[Camp Creation/Editing: Session Card Scaling](https://www.notion.so/uwblueprintexecs/Camp-Creation-Editing-Session-Card-Scaling-24e54d39cdba4d33bc1a4c97c3af2dff)
* 
1. go to `/admin/add-camp`
2. fill out first page then go to next
3. add session and see that it wraps properly in the drawer
before:
after:
*

fix: session card/drawer wrapping

---

frontend/src/components/pages/CampsList/CampsTable.tsx

https://github.com/uwblueprint/focus-on-nature/pull/196#discussion_r1055082277
https://user-images.githubusercontent.com/40974372/209657995-aaca9e2a-8725-404f-8c1a-32cfbad25223.mov
1.
*

fix: delete camp button goes below edit on popover

---

frontend/src/components/pages/RegistrantExperience/RegistrationSteps/Waiver/WaiverReducer.tsx
frontend/src/components/pages/RegistrantExperience/RegistrationSteps/Waiver/index.tsx
frontend/src/components/pages/RegistrantExperience/RegistrationSteps/index.tsx
frontend/src/components/pages/RegistrantExperience/index.tsx
frontend/src/types/waiverRegistrationTypes.ts

* Original loading code was removed in https://github.com/uwblueprint/focus-on-nature/pull/214 as we load waiver in session selection. We still need to filter waiver clauses though, as seen in: https://github.com/uwblueprint/focus-on-nature/blob/fd459f3c0baf7d08668c109daefc08475e8e87a2/frontend/src/components/pages/RegistrantExperience/Waiver/WaiverReducer.tsx#L20-L35
1. Go to waiver page, make sure everything appears as expected
*

fix: Waiver clauses not loading

---

frontend/src/components/pages/CampsList/CampsTable.tsx
frontend/src/components/pages/CampsList/index.tsx

[Camp List Table: Add a loading state when getting all the camps](https://www.notion.so/uwblueprintexecs/Camp-List-Table-Add-a-loading-state-when-getting-all-the-camps-0fc3485dea2d43178fe789239c985d43)
* 
1.
*

Camp List Table: Add a loading state when getting all the camps

---

frontend/src/components/pages/CampCreation/CampCreationFooter.tsx
frontend/src/components/pages/CampOverview/Footer.tsx
frontend/src/components/pages/CampOverview/FooterDeleteModal.tsx

[Camp edit/create CTA: Disable CTAs for camp create and edit when processing](https://www.notion.so/uwblueprintexecs/Camp-edit-create-CTA-Disable-CTAs-for-camp-create-and-edit-when-processing-b5fa2a4430c44c0986ef7b921ef70f0e)
* disabled both using same variable, not sure if that is intended behavior or if you just want to disable only `delete` when `delete` is clicked and not `publish`
1.
*

Camp edit/create CTA: Disable CTAs for camp create and edit when processing

---

frontend/src/components/pages/RegistrantExperience/RegistrationSteps/AdditionalInfo/QuestionCards/CamperQuestionsCard.tsx
frontend/src/components/pages/RegistrantExperience/RegistrationSteps/PersonalInfo/personalInfoReducer.tsx

[Registrant Experience: Camper formQuestions become empty objects from maps](https://www.notion.so/uwblueprintexecs/Registrant-Experience-Camper-formQuestions-become-empty-objects-from-maps-2f7fb75e14a04c189396be841b6ba019)
* The problem was that in making a deep copy (check changed files), the JSON.stringify/parse methods would convert the formResponses maps into empty objects since maps aren't serializable, and then using the .get method on the empty objects would fail (since they're only supposed to work on maps).
* To fix this, I added a for loop to copy over the maps from `Campers` after the `newCampers` array is made.
1. Register for any camp i.e. http://localhost:3000/register/camp/63139c7bc3d7b55b44a01531
2. Fill out step 1
3. Fill out step 2
4. Go back to step 1 and try to update …

fix: Form Responses empty object bug in Registrant Experience

---

backend/typescript/services/implementations/camperService.ts
backend/typescript/utilities/CampUtils.ts
backend/typescript/utilities/stripeUtils.ts
frontend/src/components/pages/RegistrantExperience/RegistrationResult/RegistrationErrorModal.tsx
frontend/src/components/pages/RegistrantExperience/RegistrationResult/RegistrationInfoCard.tsx
frontend/src/components/pages/RegistrantExperience/RegistrationResult/index.tsx
frontend/src/components/pages/RegistrantExperience/RegistrationResult/textStyles.ts
frontend/src/components/pages/RegistrantExperience/RegistrationSteps/AdditionalInfo/edlpSessionRegistration.tsx
frontend/src/components/pages/RegistrantExperience/RegistrationSteps/AdditionalInfo/index.tsx
frontend/src/components/pages/RegistrantExperience/RegistrationSteps/RegistrationFooter.tsx
frontend/src/components/pages/RegistrantExperience/RegistrationSteps/ReviewRegistration/PaymentSummary.tsx
frontend/src/components/pages/RegistrantExperience/RegistrationSteps/ReviewRegistration/index.tsx
frontend/src/components/pages/RegistrantExperience/RegistrationSteps/Waiver/WaiverReducer.tsx
frontend/src/components/pages/RegistrantExperience/RegistrationSteps/index.tsx
frontend/src/components/pages/RegistrantExperience/index.tsx
frontend/src/constants/RegistrationConstants.ts
frontend/src/types/CamperTypes.ts
frontend/src/types/RegistrationTypes.ts
frontend/src/types/waiverRegistrationTypes.ts
frontend/src/utils/CampUtils.ts
frontend/src/utils/RegistrationUtils.ts

[Registrant Experience: Payment Failure/Confirmation](https://www.notion.so/uwblueprintexecs/Task-Board-F22-9e03bf9f7c4343f09a8a5c16dc48a12a?p=c4a45ddbdb1f433cbf01448ede701316&pm=c)
[Payments - Stripe API](https://www.notion.so/uwblueprintexecs/Task-Board-F22-9e03bf9f7c4343f09a8a5c16dc48a12a?p=5758698f7e8d440da53b92b84082df3c&pm=c)
* Used session storage to cache session details and restore session when the user clicks "back"
* `sessionStorage` is different from `localStorage`, expires: https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage 
* Creates a bunch of components for result handling in `RegistrationResult/`
Based on work in https://github.com/uwblueprint/focus-on-nature/pull/117:
* To get around CORS errors for redirect, let's return the created checkout link and …

[4/n] Implements payment flow

---

backend/typescript/services/implementations/emailService.ts

[Waitlist: Invite a waitlisted camper to join a session (Update email)](https://www.notion.so/uwblueprintexecs/Task-Board-F22-9e03bf9f7c4343f09a8a5c16dc48a12a?p=5c05400cce514b01a5604f76b7e94315&pm=c)
* 
1. Try to invite a waitlisted camper to join a session and check the email sent to that waitlisted camper's primary contact email. 
2. Once you click on the link in that invite email, you should get taken to the registration flow for that session and only be able to register that 1 camper. 
Note: This depends on the https://github.com/uwblueprint/focus-on-nature/pull/237 PR to be merged
*

Refactor: Updates invite link in waitlist registration email

---

frontend/src/APIClients/CampsAPIClient.ts
frontend/src/components/pages/CampCreation/CampCreationFooter.tsx
frontend/src/components/pages/CampCreation/CampDetails/index.tsx
frontend/src/components/pages/CampCreation/index.tsx
frontend/src/theme/colors.ts

[Camp Creation/Editing: Upload Image & Store in Firebase ](https://www.notion.so/uwblueprintexecs/Task-Board-F22-9e03bf9f7c4343f09a8a5c16dc48a12a?p=0b7a1c33a79f47d6ad075fbf93b4ad50&pm=c)
* The backend infra is set up already
* https://uwblueprint.github.io/starter-code-v2/docs/file-storage/
*  https://cloud.google.com/storage/pricing#cloud-storage-always-free
* https://developer.mozilla.org/en-US/docs/Web/API/FormData/Using_FormData_Objects#sending_files_using_a_formdata_object
* https://stackoverflow.com/questions/11876175/how-to-get-a-file-or-blob-from-an-object-url
1.
* Camp creation and camp editing flows; keep or change image

Add image upload to camp creation

---

frontend/src/components/common/TimePicker.tsx
frontend/src/components/pages/CampCreation/CampDetails/index.tsx
frontend/src/components/pages/CampCreation/index.tsx

[Camp Creation: Unable to progress through camp creation flow on Safari](https://www.notion.so/uwblueprintexecs/Task-Board-F22-9e03bf9f7c4343f09a8a5c16dc48a12a?p=711f3a0f1a1a4c2cb878f2496bbf3017&pm=c)
* TL;DR the Safari validation was failing, it's because the `<Input>` element in Chakra doesn't work on Safari. Created a custom equivalent
* Changed one piece of logic where we want to clear values of EDLP, in case the user checks EDLP then creates values, then  unchecks EDLP -- want to make sure these values are not sent in the "create camp" call
1. Please test on other browsers
*

Fix: Safari time picker

---

frontend/src/components/pages/CampCreation/index.tsx

[Camp Creation: Camp is allowed to be made without selecting a province](https://www.notion.so/uwblueprintexecs/Task-Board-F22-9e03bf9f7c4343f09a8a5c16dc48a12a?p=a7e4d0a522a94a338f30c7794143e72b&pm=c)
* 
1.
*

fix: require province to proceed

---

frontend/src/components/pages/CampOverview/CampersTable/CampersTables.tsx
frontend/src/components/pages/CampOverview/CampersTable/WaitlistedCampersTable.tsx
frontend/src/components/pages/CampsList/index.tsx

[Camp Overview: Disable remove CTA/ close modal when the backend is processing the remove waitlisted camper CTA + reload the page on success](https://www.notion.so/uwblueprintexecs/Camp-Overview-Disable-remove-CTA-close-modal-when-the-backend-is-processing-the-remove-waitlisted--dbc73a5e64fc4e51bd2733f47e7b5fa3)
* Moved the onClose so that the modal closes before the backend call.
* Added our good ol' handle refetch so that it refetches (refreshes) the page right after the call.
1. Navigate to http://localhost:3000/admin/camp/6397f94e2ff11dcda0ba4960, or any other camp with someone on a waitlist (or add a camper to the waitlist, you'll have to do this manually right now through mongo or postman).
2. Try to remove a camper from the waitlist and spam click the remove button.
3. Make sure …

Fix: Call Remove waitlisted camper only once

---

frontend/src/components/pages/CampOverview/CampersTable/CamperDetailsBadge.tsx
frontend/src/components/pages/CampOverview/CampersTable/CampersTable.tsx
frontend/src/components/pages/CampOverview/CampersTable/CampersTables.tsx
frontend/src/components/pages/CampOverview/EditCamperModal/index.tsx
frontend/src/components/pages/CampOverview/ViewCamperModal/PickupDropoffTableRow.tsx
frontend/src/components/pages/CampOverview/ViewCamperModal/index.tsx
frontend/src/components/pages/RegistrantExperience/RegistrationSteps/RegistrationFooter.tsx
frontend/src/components/pages/RegistrantExperience/RegistrationSteps/index.tsx
frontend/src/utils/CampUtils.ts

[[Registrant Experience] Dates to select session are incorrect](https://www.notion.so/uwblueprintexecs/Registrant-Experience-Dates-to-select-session-are-incorrect-ee341f9de21d421eb8be0bc903ea4843)
* Passed in a particular session as a prop
* Using the session's dates, I can conditionally render the EDLP tags if the camper's selected EDLP dates are within the particular session's range
1. Go to http://localhost:3000/admin/camp/6396319f01dd5e987a03b516
2. Ensure that the campers that have EDLP only display the purple EDLP tags if the EDLP date is in range.
**Before:**
**After:**
* Correctness, functionality.

Fix: Display EDLP tag applicable to a session

---

backend/typescript/services/implementations/emailService.ts
frontend/src/APIClients/CamperAPIClient.ts
frontend/src/components/pages/WaitlistExperience/index.tsx

[Waitlist: Make the backend call to create the waitlisted camper(s) on submit click](https://www.notion.so/uwblueprintexecs/Waitlist-Make-the-backend-call-to-create-the-waitlisted-camper-s-on-submit-click-d3c784b0354944dca901450f082c23e2)
* Linked the backend `CamperAPIClient.waitlistCampers` call to the frontend on waitlist submission
* added error handling via toast for the any errors encountered in adding wait list campers
1. Go to http://localhost:3000/register/camp/6396319f01dd5e987a03b516
2. try to register with a valid email. This should get error
3. try to register with a valid email. Thus should lead to success and the review page being loaded
* The way I handled displaying the error message in CamperAPIClient.ts feels rather off (I use a lot of `as` keywords and type …

Waitlist backend call

---

frontend/src/components/pages/RegistrantExperience/RegistrationResult/index.tsx
frontend/src/components/pages/RegistrantExperience/RegistrationSteps/ReviewRegistration/PaymentSummary.tsx

[Add HST not required to ‘Total’ copy on payment review & confirmation page](https://www.notion.so/uwblueprintexecs/Add-HST-not-required-to-Total-copy-on-payment-review-confirmation-page-ef4d474b8ae0423fa79bf08a383e9ab0?pvs=4)
* Added an italicized `<Text>`
1. Register a camper.
2. 
* Correctness.

Add HST not required to ‘Total’ copy on payment review & confirmation page

---

backend/typescript/middlewares/validators/adminValidators.ts
backend/typescript/middlewares/validators/campValidators.ts
backend/typescript/middlewares/validators/camperValidators.ts
frontend/src/components/pages/CampOverview/EditCamperModal/index.tsx

[Fix camper edit functionality](https://www.notion.so/uwblueprintexecs/Fix-camper-edit-functionality-12b9fad2bae24cce9cf7352535ebc406)
* Added a useEffect to ensure the changes were loaded every time there was a new camper clicked
* Added a useMemo to keep track of initial state to set back to if an admin clicks cancel (very similar to what I did for all the edit components in the ReviewRegistration step, registrant experience).
1. Navigate to any camp with campers, http://localhost:3000/admin/camp/6397f94e2ff11dcda0ba4960 works well.
2. Try to edit (multiple) campers, the initial information loaded should all be correct now and of the clicked camper.
3. Click save, cancel, click outside of the modal (another way to cancel), and ensure everything behaves as expected now.
* Correctness, …

Fix camper edit functionality

---

frontend/src/components/pages/RegistrantExperience/RegistrationSteps/RegistrationFooter.tsx
frontend/src/components/pages/RegistrantExperience/RegistrationSteps/RegistrationNavStepper.tsx
frontend/src/components/pages/RegistrantExperience/RegistrationSteps/ReviewRegistration/ReviewInformation/EditAdditionalQuestionsCard.tsx
frontend/src/components/pages/RegistrantExperience/RegistrationSteps/ReviewRegistration/ReviewInformation/EditCamperCard.tsx
frontend/src/components/pages/RegistrantExperience/RegistrationSteps/ReviewRegistration/ReviewInformation/EditContactCard.tsx
frontend/src/components/pages/RegistrantExperience/RegistrationSteps/ReviewRegistration/ReviewInformation/EditEDLPCard.tsx
frontend/src/components/pages/RegistrantExperience/RegistrationSteps/ReviewRegistration/ReviewInformation/index.tsx
frontend/src/components/pages/RegistrantExperience/RegistrationSteps/ReviewRegistration/index.tsx
frontend/src/components/pages/RegistrantExperience/RegistrationSteps/index.tsx

[[Registrant Experience] Prevent user from proceeding if anything on review page is currently being edited](https://www.notion.so/uwblueprintexecs/Registrant-Experience-Prevent-user-from-proceeding-if-anything-on-review-page-is-currently-being-ed-10bb5b79972647989cc3d1b3f9716e66?pvs=4)
* Added another piece of state, called `isEditing`, which is a number that counts the amount of components being edited (0 means nothing is being edited)
* This does in some sense create another source of truth for whether something is editing or not (global vs local state for each edit card), so I made sure to be careful and increment/decrement only when saving or canceling, so registrant's never get stuck on the review page.
1. Go to http://localhost:3000/register/camp/6396319f01dd5e987a03b516 and try …

[Registrant Experience] Prevent user from proceeding if anything on review page is currently being edited

---

frontend/package.json
package.json

[Firebase build (staging) not working](https://www.notion.so/uwblueprintexecs/Firebase-build-staging-not-working-01b4a6d16be34448a3a546d76367679d?pvs=4)
* Added a flag to the build command that uses a legacy provider to solve the error (which happens due to the newer version of nodejs)
1. See if deployment is successful.
* Ensure it works.

Add legacy openssl flag to build command

---

backend/typescript/middlewares/validators/campValidators.ts
backend/typescript/rest/campRoutes.ts
frontend/src/APIClients/CampsAPIClient.ts

[[Management Experience] Manage sessions doesn’t persist](https://www.notion.so/uwblueprintexecs/Management-Experience-Manage-sessions-doesn-t-persist-cec1071f9d9a4cd980973cc6a9e388ab?pvs=4)
* Changed the format of the patch so that it would actually use the authorization headers
* Changed the validators too to account for this.
1. Note: This is only going to work after pr #267 is merged.
2. Go to any camp and click the manage sessions button on the right.
3. Changing session capacity should work now, deletion worked anyway.
* Correctness, functionality.

Fix: Manage sessions doesn’t persist

---

backend/typescript/models/waitlistedCamper.model.ts
backend/typescript/services/implementations/campService.ts
backend/typescript/services/implementations/camperService.ts
backend/typescript/types.ts
frontend/src/components/pages/CampOverview/CampersTable/WaitlistedCampersTable.tsx
frontend/src/types/CamperTypes.ts

[Camp Overview: Sort waitlisted campers by created at date](https://www.notion.so/uwblueprintexecs/Camp-Overview-Sort-waitlisted-campers-by-created-at-date-d3df8b367eba444a988a58c56fc7f6ce?pvs=4)
* Added a registrationDate property to waitlisted camper DTOs and schema, and also implemented it whereever needed (pretty much look at whereever waitlisted campers were being used and added the new property there, trying to recreate what we did with the regular camper dtos).
1. Note: This PR will only work properly after PR #267 is submitted, so I'll draft it until then.
2. Register some campers on a waitlist
3. Ensure that they are sorted in the order you created them in (by registrationDate).
* Correctness, functionality.

Camp Overview: Sort waitlisted campers by created at date

---

backend/typescript/Dockerfile

Comment out old line that was causing:

fix: docker build failing on old line

---

frontend/src/components/pages/CampCreation/ScheduleSessions/SidePanel/CurrentSessionsView.tsx
frontend/src/components/pages/CampCreation/ScheduleSessions/SidePanel/ScheduledSessionsCard.tsx
frontend/src/components/pages/CampCreation/ScheduleSessions/SidePanel/SessionSidePanel.tsx
frontend/src/components/pages/CampCreation/ScheduleSessions/SidePanel/index.tsx
frontend/src/components/pages/CampCreation/ScheduleSessions/index.tsx
frontend/src/components/pages/CampCreation/index.tsx

[[Camp Creation] Ensure at least one date is selected for each session](https://www.notion.so/uwblueprintexecs/Camp-Creation-Ensure-at-least-one-date-is-selected-for-each-session-f0b82559812e4b7ebff5f7cf4c528f42?pvs=4)
* Added flag in `CurrentSessionsView.tsx` to keep track of error handling 
* Wrapped ScheduledSessionsCard with chakra FormControl and associated FormErrorMessage
* Prevented user from clicking next button if any ScheduledSessionCard had no dates selected
1. Enter Add a camp flow `admin/add-camp`
2. Fill out camp details and click Next
3. Select some dates and add a camp session
4. Edit camp session to have no dates
5. Click Next
6. Error message is displayed and user cannot proceed to the next step
*

fix: Add current session date validation on camp creation flow

---

backend/typescript/services/implementations/emailService.ts

[Sort session dates in waitlist registration email](https://www.notion.so/uwblueprintexecs/Sort-session-dates-in-waitlist-registration-email-1783b7485e8b443d99c1f43a89a2f663)
* Added a sorting function for camp session dates before converting dates into strings for parent emails.
1. Go to http://localhost:3000/register/camp/6484d0b47f142e45f5c30afe. There should be a total of 4 different sessions with varying session dates. Click on any random one
2. Fill in the required fields and register/waitlist a "camper" using an accessible email.
3. Once registration is completed, check the email for an email from FON. The dates under "Session Dates" should be sorted from earliest to latest
* Check if sorting works across all different session dates

fix: sorted session dates in registration emails

---

frontend/src/components/pages/RegistrantExperience/RegistrationSteps/QuestionGroups/MultiselectGroup.tsx

[Additional Info Checkbox work for options with a comma in it](https://www.notion.so/uwblueprintexecs/Additional-Info-Checkbox-work-for-options-with-a-comma-in-it-1a30e34ab60447e4a2b13c80983ad12e)
* Changed multiselect boxes delimiter from "," to "@" (less predictable symbol) to separate the set of selected options because one multiselect option contains ","
1. Go to http://localhost:3000/register/camp/6396319f01dd5e987a03b516
2. Select an available camp session. If none present, create one and select it.
3. Fill in all required fields in "Personal Info" section. Select "Next".
4. Under "Additional Info" section, under "Camper-specific Additional Questions", try different combinations of enabling and disabling all options. Then, fill in other required information in this section. Select …

fix: allow user to deselect multiselect options containing commas

---

frontend/src/components/common/formQuestions/AddQuestionModal/QuestionOptionSection.tsx

[Camp Editing: Changing from text to multiple choice doesn’t render option](https://www.notion.so/uwblueprintexecs/Camp-Editing-Changing-from-text-to-multiple-choice-doesn-t-render-option-419cad42c01d477392290b1530eff18c?pvs=4)
* checked if `optionsToBeEdited` array was empty; if empty, set `option` field to empty string to render an empty options field for "Multiple choice" and "Checkbox"
1. Go to [site](http://localhost:3000/admin/edit-camp/63b01ddec71ee220ef84daeb)
2. Click "Step 3/3 Registration Form" header
3. Expand "Camper Information" accordion dropdown
4. Click "Edit" on "10. How does the camper feel about rock climbing?" 
5. Click "Question Type" and change from "Short answer" to "Multiple choice" or "Checkbox" (if "Question type" is already set to "Short answer", select another …

fix: allow user to change from short answer to multiple choice with rendered default option

---

frontend/src/components/pages/RegistrantExperience/index.tsx

[Payment Failed Modal](https://www.notion.so/uwblueprintexecs/Payment-Failed-Modal-b7228f36e326471696f0aa9efac733a0)
* Add check to prevent current step to be set to registration after checkout has been completed
1. Go through the register flow to signup for a camp
2. Verify that checkout is successful and directed to registration result page (example below)
* If checkout fails the error modal should be displayed

tina-nathan/payment-failed-modal

---

frontend/src/components/pages/WaitlistExperience/PersonalInfo/personalInfoReducer.tsx

[Add form validation to verify valid email during registration](https://www.notion.so/uwblueprintexecs/Add-form-validation-to-verify-valid-email-during-registration-8790ebe9393a4409bce0f7bc6a3d62f8)
* Add regex check using existing email checking that matches with basic email addresses
1. Start the register flow to signup for a camp
2. When on Personal Info page, fill out necessary information except email in Primary Contact
3. Try:
- leaving Email field blank and click Next -> verify error message "Form does not pass validation" pops up
- enter a random sequence of characters in Email field and click Next -> verify error message "Form does not pass validation" pops up
- enter `user@.com` and click Next -> verify error message "Form does not pass validation" pops up
- enter `user.@com` …

Add form validation to email in registration

---

backend/typescript/rest/camperRoutes.ts
backend/typescript/services/implementations/camperService.ts
backend/typescript/services/interfaces/camperService.ts
frontend/src/APIClients/CamperAPIClient.ts
frontend/src/components/pages/CamperRefundCancellation/CamperRefundFooter.tsx
frontend/src/components/pages/CamperRefundCancellation/CamperRefundInfoCard.tsx
frontend/src/components/pages/CamperRefundCancellation/index.tsx

[Cancellation-Refund-Populate-camper-selection-page-with-real-data-edge-cases](https://www.notion.so/uwblueprintexecs/Cancellation-Refund-Populate-camper-selection-page-with-real-data-edge-cases-a593a616bdba48fb88206b909a79dbdb)
* Implemented a `GET` endpoint that retrieves discount information from stripe
* Leveraged the endpoint to display discount information (if any). Here is a screenshot of what it looks like:<img width="942" alt="image" src="https://github.com/uwblueprint/focus-on-nature/assets/57463206/eb3a1169-3f73-470e-9fd9-f2be1648564f"> _**Note**: When the initial Spinner/loading screen will continue until the information from stripe is successfully retrieved, aka error handled gracefully._
* Added logic to display a banner when sessions are disabled and have the **Total Refund …

Catherine derrick/error banner and coupon display

---

frontend/src/components/pages/CampCreation/CampDetails/index.tsx
frontend/src/components/pages/CampCreation/index.tsx

[Add validation to prevent negative amounts for EDLP during camp creation](https://www.notion.so/uwblueprintexecs/Add-validation-to-prevent-negative-amounts-for-EDLP-during-camp-creation-04780e5457824f33837c44ec2599f8f6?pvs=4)
* Add validation that EDLP amount is non-negative during camp creation
1. Navigate to http://localhost:3000/admin/add-camp
2. Fill out necessary information
3. Checkbox "Camp offers early drop-off and late pick-up"
4. Try:
* enter 0 and click Next -> verify error message "You must add a non-negative fee" pops up and Next button is disabled
* enter -10 and click Next -> verify error message "You must add a non-negative fee" pops up and Next button is disabled
* enter 10 and click Next -> verify can successfully click Next to go to next step
* Error is displayed when …

feat: add validation for non-negative EDLP amount
