- hooks/post-merge
- secret.config
[Ticket Name](https://www.notion.so/uwblueprintexecs/Task-Board-38b49f83f6ce4b07ae188dabb37631e8?p=a4767b57a00f4d3099fd86c50b26ed57)
* Add vault access for accessing project secrets. 
1. Run `vault kv get -format=json kv/focus-on-nature | python3 update_secret_files.py` in project root. 
*
> feat: update vault path

- backend/typescript/models/waitlistedCamper.model.ts
[Ticket Name](https://www.notion.so/uwblueprintexecs/Waitlist-Model-8b5903196b54494caee64ad2a1dd9451)
* Added waitlistedCamper model
1. add waitlistedCamper model to index.ts
2. run application and ensure atlas is populated
* waitlisted camper model has the correct elements.
> feat: create waitlisted camper model

- backend/typescript/models/waitlistedCamper.model.ts
- backend/typescript/types.ts
[Waitlist DTO](https://uwblueprintexecs.notion.site/Waitlist-DTO-3e1e62b1d2fd4199b0fb6b8bc70fcd5e)
*  added waitlisted camper DTO to types.ts 
1. make sure the DTO is implemented correctly 
*  are all the required fields present 
*  are all the types correct --> is camps a string[ ] or just string?
> feat: create waitlisted camper DTO

- backend/typescript/middlewares/validators/userValidators.ts
- backend/typescript/middlewares/validators/util.ts
- backend/typescript/models/campleader.model.ts
- backend/typescript/services/implementations/__tests__/userService.test.ts
- backend/typescript/services/implementations/authService.ts
- backend/typescript/testUtils/testDb.ts
- backend/typescript/types.ts
- frontend/src/APIClients/AuthAPIClient.ts
- frontend/src/APIClients/EntityAPIClient.ts
- frontend/src/components/auth/Logout.tsx
- frontend/src/components/auth/RefreshCredentials.tsx
- frontend/src/components/crud/CreateForm.tsx
- frontend/src/components/crud/DisplayTableContainer.tsx
- frontend/src/components/crud/UpdateForm.tsx
- frontend/src/components/pages/__tests__/Default.test.tsx
[Update User APIs/Validator for login](https://www.notion.so/uwblueprintexecs/Update-User-APIs-Validator-for-login-2e9fadfa340543baa0a5801bba41b00c)
[Domain Validation on Login](https://www.notion.so/uwblueprintexecs/Domain-Validation-on-Login-4d8ceda6f09b4d298a6f214d1bf99333)
* modified validators for user creation from validating a string as a password to validating a boolean for the active state
* added server side validation for Google domains to login (and also create a user). restricted to `focusonnature.ca` and `uwblueprint.org`
* modified call to user creation in auth service to create a CampLeader by default
* NOTE: was not able to find a way to add 2 domains to the client-side validation through the hostedDomain prop. Can definitely specify one domain though
1. Use Postman to …
> feat: user creation and authentication with google updates

- backend/typescript/services/implementations/emailService.ts
- backend/typescript/services/interfaces/emailService.ts
[Email Service](https://www.notion.so/uwblueprintexecs/Task-Board-38b49f83f6ce4b07ae188dabb37631e8?p=5f76ef1b363449dfa4f54480aede8ef5)
* Created custom email services in `implementations/emailService.ts` for sending a confirmation email, sending a cancellation email, sending a waitlist email to a parent and sending a waitlist email to an admin. 
1. Paste the following endpoint in `userRoutes.ts` and update the `test@uwblueprint.org` email. 
```
userRouter.get("/testEmailService", async (req, res) => {
res.status(200).json("")
try {
await emailService.sendConfirmationEmail("test@uwblueprint.org")
await emailService.sendCancellationEmail("test@uwblueprint.org")
await emailService.sendWaitlistAdminEmail("test@uwblueprint.org")
await emailService.sendWaitlistEmail("test@uwblueprint.org") …
```
> feat: setup email service methods

- backend/typescript/middlewares/validators/campValidators.ts
- backend/typescript/middlewares/validators/camperValidators.ts
- backend/typescript/middlewares/validators/formQuestionValidators.ts
- backend/typescript/middlewares/validators/util.ts
- backend/typescript/models/baseCamp.model.ts
- backend/typescript/models/camper.model.ts
- backend/typescript/models/formQuestion.model.ts
- backend/typescript/models/formTemplate.model.ts
- backend/typescript/rest/campRoutes.ts
- backend/typescript/rest/camperRoutes.ts
- backend/typescript/services/implementations/campService.ts
- backend/typescript/services/implementations/camperService.ts
- backend/typescript/services/interfaces/campService.ts
- backend/typescript/types.ts
[Registration form - Camp API updates](https://www.notion.so/uwblueprintexecs/Tasks-38b49f83f6ce4b07ae188dabb37631e8?p=7ff572a8847548dd8e7f7491f4cb69aa)
* Remove camperInfo and change to formQuestions
* Added in a new Validator for formQuestions
* Construct formQuestions, then baseCamps, then Camp
* Implemented exception guarantee
1. {
"name": "jason-test",
"description": "'description'",
"location": "'knoxville'",
"capacity": 20,
"fee": 3000,
"formQuestions": [{
"type": "Text",
"question": "What is it",
"required": true,
"description": "Question question",
"options": ["one", "two"]
}],
"dates": ["12-2-2021", "12-30-2022"],
"startTime": "12:40",
"endTime": "16:50",
"ageLower": 12,
"ageUpper": 23,
"active": true
}
* createCamp implementation
* formQuestion and createCamp validators
> feat: refactor camp api

- backend/typescript/middlewares/validators/camperValidators.ts
- backend/typescript/models/camper.model.ts
- backend/typescript/rest/camperRoutes.ts
- backend/typescript/services/implementations/camperService.ts
- backend/typescript/services/interfaces/camperService.ts
- backend/typescript/types.ts
[Ticket Name](https://www.notion.so/uwblueprintexecs/Tasks-38b49f83f6ce4b07ae188dabb37631e8?p=63fbd360033049debb58fcd3a6c7a699)
* Added `camper/cancel/:chargeId` route allowing for cancellation of registration for all campers under the transaction's charge ID
* This endpoint will first check if eligible for cancellation: must be cancelling >= 30 days before start of camp, there are campers with the charge ID, the camp exists
1. Test manually in Postman - create a PUT request to the endpoint with a charge ID
2. Test multiple cases: if there are no campers with the charge ID, camp that is associated with the campers being deleted doesn't exist, test all edge cases for the 30 day eligibility for deletion, then ensure that for a valid deletion that the campers from the camp are deleted and …
> feat: create cancellation API

- backend/typescript/middlewares/validators/adminValidators.ts
> fix: lint error

- backend/typescript/rest/adminRoutes.ts
- backend/typescript/services/implementations/emailService.ts
- backend/typescript/services/interfaces/emailService.ts
[Update Email Service](https://www.notion.so/uwblueprintexecs/Tasks-38b49f83f6ce4b07ae188dabb37631e8?p=fc2f2b6bf4b346b9a0f8fc964bf418f7)
* 
1. Add following lines to server.ts but replace \<INSERT EMAIL\> with your email.
```
import IEmailService from "./services/interfaces/emailService";
import EmailService from "./services/implementations/emailService";
import nodemailerConfig from "./nodemailer.config";
const emailService: IEmailService = new EmailService(nodemailerConfig);
const email = "<INSERT EMAIL>";
const campers: any = [
{ name: "Anne Chung", age: 22 },
{ name: "Peppa Pig", age: 12 }
];
emailService.sendConfirmationEmail(
email,
"Anne Chung",
"Camp 1",
"Your mom's house ;)",
"March 1st, 2022",
campers,
"911",
20,
40,
10,
120,
"https://www.youtube.com/watch?v=dQw4w9WgXcQ",
); …
```
> feat: update email service

- backend/typescript/middlewares/validators/camperValidators.ts
- backend/typescript/models/camper.model.ts
- backend/typescript/rest/camperRoutes.ts
- backend/typescript/services/implementations/campService.ts
- backend/typescript/services/implementations/camperService.ts
- backend/typescript/types.ts
[Update Camper Model](https://www.notion.so/uwblueprintexecs/Tasks-38b49f83f6ce4b07ae188dabb37631e8?p=131b7220c3704954a7e4de3231b9460b)
1. Try sending POST request to /camper/register
```
{
"campSession": "6229a30c827c860059d14407",
"firstName": "anne",
"lastName": "chung",
"age": 12,
"allergies": "you",
"hasCamera": true,
"hasLaptop": false,
"contacts": [
{
"firstName": "Mommy",
"lastName": "?",
"email": "mommyyy@gmail.com",
"phoneNumber": "1234"
},
{
"firstName": "Daddy",
"lastName": "?",
"email": "daddy@gmail.com",
"phoneNumber": "1234"
}
],
"registrationDate": "2022-04-06",
"hasPaid": false,
"chargeId": "hi",
"charges": {
"camp": 20,
"earlyDropoff": 0,
"latePickup": 0
}
}
```
2. Try sending PUT to /camper
3. Verify fields are updated correctly.
*
> refactor: add required fields to camper model

- backend/typescript/middlewares/validators/userValidators.ts
- backend/typescript/models/campcoordinator.model.ts
- backend/typescript/models/user.model.ts
- backend/typescript/rest/entityRoutes.ts
- backend/typescript/services/implementations/__tests__/userService.test.ts
- backend/typescript/services/implementations/authService.ts
- backend/typescript/services/implementations/camperService.ts
- backend/typescript/services/implementations/userService.ts
- backend/typescript/swagger.yml
- backend/typescript/types.ts
Task 1 for [Update users - role fix](https://www.notion.so/uwblueprintexecs/Update-users-role-fix-4c87f9e742cf4bcebd445d8a4af24f9d)
* Changed `campLeader` to `campCoordinator` everywhere it appears
1. Can try testing the user update API
* Anywhere I might have missed a change? Works when I built/ran the code though.
> refactor: campLeader to campCoordinator

- backend/typescript/models/camp.model.ts
- backend/typescript/models/campSession.model.ts
> Add productId and priceId to Camp model

- frontend/src/APIClients/BaseAPIClient.ts
[Fix: Logout](https://www.notion.so/uwblueprintexecs/Fix-Logout-885b4b0cdef44e078b5a471961fe49d3)
* Implemented the fix as in this: https://github.com/uwblueprint/starter-code-v2/pull/162
1. Login and then wait ~ 1 hour
2. Logout and make sure no errors are seen on the console
* If it works!
> fix: logout bug

- backend/typescript/models/waitlistedCamper.model.ts
- backend/typescript/services/implementations/camperService.ts
- backend/typescript/types.ts
[Ticket Name](https://www.notion.so/uwblueprintexecs/Waitlist-Model-Update-Setting-invite-expires-on-field-f5c661ad32d244108fcbbe2f412fa3e9)
* Added linkExpiry to model
1. add waitlisted camper using the /campers/waitlist endpoint (POST)
2. grab waitlistedCamper id and use /campers/waitlist/:waitlistedCamperId (PATCH)
3. check if link expiry exists in Atlas and is 3 days ahead
* Ensure time is 3 days ahead
> feat: add linkExpiry to WaitlistedCamper model

- backend/typescript/services/implementations/emailService.ts
[Ticket Name](https://www.notion.so/uwblueprintexecs/Waitlist-Updating-email-link-for-waitlisted-camper-invite-ea1dc65ac6774a60b36d2a94a1e32c95)
* Changed link for inviting a waitlisted camper, thats it.
1. check if the link is right and the email sends with the right link.
* the link being right
> Bugfix/Updated Waitlist Camper Invite Link

- frontend/src/components/common/camps/CampSessionInfoHeader.tsx
- frontend/src/components/pages/CampsPage.tsx
[Camp Overview: Session Navigation Component](https://www.notion.so/uwblueprintexecs/Camp-Overview-Session-Navigation-Component-51a6ae1b817d42d59df61a1a0c874154)
* Created a CampSessionInfoHeader component in frontend/src/components/common/camps
* Added sample data for testing in CampsPage (only there for testing, should be removed later) 
^^Note* chevrons are styled a bit differently from the Figma - have already let the designers know and they said it's ok!
1. Go to camps page (may need to click to a different tab and then onto the camps tab again)
2. Click on the left and right chevrons to scroll through the camp sessions
* Is the component working as desired? 
* Is the styling consistent with design specs
> feat: session navigation component

- backend/typescript/middlewares/validators/camperValidators.ts
- backend/typescript/models/camper.model.ts
- backend/typescript/types.ts
[Add relationshipToChild field to registered camper](https://www.notion.so/uwblueprintexecs/Registration-Add-relationshipToChild-field-to-registered-camper-6efd6ff9b73b463786eeb48b65c0a37e)
* Added relationshipToChild: string field to camper model 
* Added the relationshipToChild field to camper DTO 
* Added the relationshipToChild checks in the validator
1. Run the backend endpoints Create and Update camper with the new field in the contact info to make sure nothing broke
*
> feat: added relationshipToChild field in DTOs and models

- backend/typescript/middlewares/validators/campValidators.ts
- backend/typescript/middlewares/validators/formQuestionValidators.ts
- backend/typescript/models/formQuestion.model.ts
- backend/typescript/services/implementations/campService.ts
- backend/typescript/types.ts
[Camp Creation: Add category to form question](https://www.notion.so/uwblueprintexecs/Camp-Creation-Add-category-to-form-question-d9c1f939a5594a3a9ea0a83769d577a3)
* Adding a `category` field to the FormQuestion model with the following possible values: `["PersonalInfo", "CampSpecific", "EmergencyContact"]`
1. Test that form question creation and edit APIs still work.
*
> feat: add category field to form question

- .github/workflows/firebase-hosting-merge.yml
- .github/workflows/heroku-deploy-dev-ts.yml
- backend/typescript/Procfile
- backend/typescript/package.json
- backend/typescript/server.ts
[Ticket Name](https://www.notion.so/uwblueprintexecs/Create-a-Staging-Environment-1d349bf00d684ead9cbe74d27cf6f7ea)
* Created staging environment for both frontend and backend (firebase for frontend and heroku for backend)
1. ensure that deployed links work as intended
* Ensure oauth is working correctly
> feat: deploy to staging environment on merge

- .github/workflows/firebase-hosting-merge.yml
- .github/workflows/firebase-hosting-pull-request.yml
- .github/workflows/heroku-deploy-dev-ts.yml
- backend/typescript/server.ts
- frontend/.firebaserc
The backend and frontend are deployed to https://focus-on-nature.herokuapp.com/ and https://focus-on-nature.web.app/admin/login respectively.
Backend: 
1. Send requests to staging backend and check that email sending still works (e.g. adding a user to the waitlist).
Frontend: 
1. Check that logging in still works.
> chore: clean up staging deployments

- frontend/src/components/pages/CampOverview/CampersTable/CampersTable.tsx
- frontend/src/components/pages/CampOverview/EditCamperModal.tsx
added a selected camper state so everyone who needs the kebab menu ca…n use this to render their modals
Not really a part of a ticket (maybe edit modal), but this is a quick push so that @twilkhoo and @uyxela can use the state to render their modals
* added a state variable to set the selected camper on the campersTable file 
* Will use this state to pass info on all the modals related to that particular camper
1. Go to http://localhost:3000/admin/camp/63139c7bc3d7b55b44a01531 
2. Try to edit a camper by going to the kebab menu -> edit 
3. You should see the edit modal with the selected camer's first name
* just want to make sure setting this state is the best way of doing this
> Fix Edit Camper Entry Point

- frontend/src/components/pages/CampOverview/Footer.tsx
[Camp Overview: Footer + Actions](https://www.notion.so/uwblueprintexecs/Camp-Overview-Footer-Actions-9ef2fa77aa924218b4a425ba60d37b43)
* Added publish action to camp overview footer
1. Create new camp
2. Go to camp overview page for said camp and use the publish flow
* I used useHistory to rerender the page because I'm not sure how much would change when it gets published. If there's a better way to do this then let me know.
> feat: add camp overview footer (publish)

- frontend/src/components/common/camps/CampSessionInfoHeader.tsx
- frontend/src/components/pages/CampOverview/ManageSessions/ManageSessionsModal.tsx
- frontend/src/components/pages/CampOverview/ManageSessions/ManageSessionsModalTable.tsx
- frontend/src/components/pages/CampOverview/index.tsx
- frontend/src/theme/colors.ts
- frontend/src/theme/index.ts
- frontend/src/theme/layerStyles.ts
- frontend/src/theme/textStyles.ts
- frontend/src/types/CampsTypes.ts
- frontend/src/utils/CampUtils.ts
[Camp Overview: Delete Session + Change Session Capacity ](https://www.notion.so/uwblueprintexecs/Camp-Overview-Delete-Session-Change-Session-Capacity-6d18cb517d61447ab691f8a7d37978f6)
This PR handles creating the modal; followup pieces of work for this ticket:
1. Creating DELETE, PATCH endpoints
2. Attaching to endpoints with API clients
* Create the modal component, passing `onOpen`, `onClose`, `isOpen` props to control open and close
* Create a table component within the modal
* Move some utility methods to `CampUtils`
1. Go to a camp page, such as http://localhost:3000/admin/camp/630a63450eb59852f9d01b1e, click the new "Manage Sessions" modal and play around. There's no actual database interactions... look at delete button (and that everything is appropriately disabled), input fields …
> Create Manage Session Modal

- frontend/src/APIClients/AdminAPIClient.ts
- frontend/src/components/pages/GlobalForms/WaiverTab/WaiverSectionCard.tsx
- frontend/src/components/pages/GlobalForms/WaiverTab/index.tsx
- frontend/src/components/pages/GlobalForms/index.tsx
- frontend/src/types/AdminTypes.ts
Not a ticket. I just added a temporary TEXT component at the waiver section for the empty state where no clauses are in the database. 
* 
1. go on the waiver tab and make sure there are no clauses in the db
* The rest of the changes are just because I linted the files
> added a temporary empty clauses state

- backend/typescript/middlewares/validators/camperValidators.ts
1. Submit request without array body (just as `{}` object)
* Just a quick fix, logic and message make sense?
> Add error check for non-array request body

- frontend/src/App.tsx
- frontend/src/components/pages/CampCreation/CampDetails/index.tsx
- frontend/src/components/pages/CampCreation/RegistrationForm/index.tsx
- frontend/src/components/pages/CampCreation/ScheduleSessions/index.tsx
- frontend/src/components/pages/CampCreation/index.tsx
- frontend/src/components/pages/CampsList/CampsNavigationHeading.tsx
- frontend/src/components/pages/CampsPage.tsx
- frontend/src/constants/Routes.ts
* Very basic setup work for add camp
1. Go to `/admin/camp/add-camp` and enjoy
2. Buttons should toggle components
* See comments
https://user-images.githubusercontent.com/40974372/198850524-af882bd3-971e-460d-8025-838d6c19d631.mov
> Create dummy files and components for add camp flow

- backend/typescript/middlewares/validators/campValidators.ts
- backend/typescript/middlewares/validators/camperValidators.ts
- backend/typescript/middlewares/validators/util.ts
- backend/typescript/services/implementations/campService.ts
* Ages and capacities should be integers, but fees can be floats?
* See comments
1. Try UPDATE endpoint with floats
2. Try POST and PATCH camp endpoints with invalid JSONs
> Bugs: Allow non-integer fee values, UPDATE endpoint fixes

- frontend/src/App.tsx
- frontend/src/components/pages/CampsList/index.tsx
[Change default URL to point to camp list](https://www.notion.so/uwblueprintexecs/Change-default-URL-to-point-to-camp-list-2d491f387e8349fa9f3dd1011a5e682f)
* Render the `<CampsPage>` instead of `<LandingPage>`
* Change `<Route>`  to `<PrivateRoute>` for home page route
NA
* App.tsx (Line 62)
> Change default URL to point to camp list

- backend/typescript/rest/campRoutes.ts
- backend/typescript/rest/entityRoutes.ts
- backend/typescript/rest/userRoutes.ts
No Ticket- just fixing some linting issues caused on dev from an accidental commit to dev
* 
1.
*
> fixing lint issues on dev branch

- frontend/src/App.tsx
- frontend/src/components/pages/RegistrantExperience/AdditionalInfo/index.tsx
- frontend/src/components/pages/RegistrantExperience/PersonalInfo/index.tsx
- frontend/src/components/pages/RegistrantExperience/ReviewRegistration/index.tsx
- frontend/src/components/pages/RegistrantExperience/Waiver/index.tsx
- frontend/src/components/pages/RegistrantExperience/index.tsx
- frontend/src/constants/Routes.ts
* Pretty similar to CampCreation
1. Open `/register/camp/:id`
* Naming of pages
> Create base components and file structure for registration

- frontend/src/components/pages/CampsList/CampsTable.tsx
[Camp List: Empty state for camp list table](https://www.notion.so/uwblueprintexecs/Camp-List-Empty-state-for-camp-list-table-bddab42a182c4e1e933dc3466b6ca791)
* Adds empty state for camp list table
1. Search for something that has no results
2. Verify empty state shows
> feat: Add empty state for camps table

- frontend/src/components/pages/CampCreation/CampCreationNavStepper.tsx
- frontend/src/components/pages/CampCreation/CampCreationPages.ts
- frontend/src/components/pages/RegistrantExperience/AdditionalInfo/index.tsx
- frontend/src/components/pages/RegistrantExperience/PersonalInfo/index.tsx
- frontend/src/components/pages/RegistrantExperience/RegistrationExperienceSteps.ts
- frontend/src/components/pages/RegistrantExperience/RegistrationNavStepper.tsx
- frontend/src/components/pages/RegistrantExperience/ReviewRegistration/index.tsx
- frontend/src/components/pages/RegistrantExperience/Waiver/index.tsx
- frontend/src/components/pages/RegistrantExperience/index.tsx
[Registration Form: Stepper Component](https://www.notion.so/uwblueprintexecs/Task-Board-F22-9e03bf9f7c4343f09a8a5c16dc48a12a?p=4ee2179957da4750890d8c7c6f6eaa61&pm=c)
* Strong inspiration from https://github.com/uwblueprint/focus-on-nature/pull/145 (uses same `StepperTab` component, almost identical logic)
* 4 steps here
1. Go to `http://localhost:3000/register/camp/<anything>` and click between steps, check that completion logic is right
https://user-images.githubusercontent.com/40974372/202889701-f3b2fcc7-e74e-4c64-baf7-e74b21a52590.mov
* Anything out of the ordinary here?
> Add stepper to registrant experience

- frontend/src/components/common/DeleteModal.tsx
- frontend/src/components/common/GeneralDeleteModal.tsx
- frontend/src/components/pages/CampCreation/ScheduleSessions/AddSessionsForm.tsx
- frontend/src/components/pages/CampCreation/ScheduleSessions/CurrentSessionsView.tsx
- frontend/src/components/pages/CampCreation/ScheduleSessions/ScheduledSessionsCard.tsx
- frontend/src/components/pages/CampCreation/ScheduleSessions/SessionDayButton.tsx
- frontend/src/components/pages/CampCreation/ScheduleSessions/SessionSidePanel.tsx
- frontend/src/components/pages/CampOverview/CampersTable/WaitlistedCampersTable.tsx
- frontend/src/theme/components/Button.ts
- frontend/src/utils/CampUtils.ts
[Camp Creation/Editing: Scheduling Sessions - Edit Session Days/Delete Session](https://www.notion.so/uwblueprintexecs/Camp-Creation-Editing-Scheduling-Sessions-Edit-Session-Days-Delete-Session-5d9b60c536b74fbe94161853a945c412)
* Refactored `RemoveCamperModal` in common to `GeneralDeleteModal`
* Use `GeneralDeleteModal` in `CurrentSessionsView` to delete scheduled sessions 
* Created `updateSelectedSessionDays` function to handle updating a scheduled session's dates
Delete a session: 
https://user-images.githubusercontent.com/46568041/202869729-9b6854e8-95da-4ea0-a8ef-fcb856519e66.mov
Delete all sessions: 
https://user-images.githubusercontent.com/46568041/202869918-6c0701e6-fb50-4b83-9af7-735edd5cdda9.mov
Update a session: 
https://user-images.githubusercontent.com/46568041/202869780-6a90 …
> feat: edit and delete sessions

- frontend/src/components/pages/CampOverview/CampersTable/CampersTable.tsx
- frontend/src/components/pages/CampOverview/CampersTable/CampersTables.tsx
- frontend/src/components/pages/CampOverview/index.tsx
- frontend/src/utils/CSVUtils.ts
> Fix frontend linter issues

- frontend/src/components/pages/CampCreation/CampDetails/index.tsx
- frontend/src/components/pages/CampCreation/RegistrationForm/index.tsx
- frontend/src/components/pages/CampsList/CampsTable.tsx
- frontend/src/components/pages/CampsList/PreviewCampDrawer.tsx
* Regression from https://github.com/uwblueprint/focus-on-nature/pull/140 (changes in margin handling)
* Linter fixes
1. Check on different screen sizes
https://user-images.githubusercontent.com/40974372/204481320-576a17b1-1d2e-47ec-b3db-0f1f4d087082.mov
*
> fix: margins in camp creation page

- frontend/src/components/common/NavBar.tsx
- frontend/src/constants/Routes.ts
[Registrant Experience: Hide navbar for registration experiencee](https://www.notion.so/uwblueprintexecs/Task-Board-F22-9e03bf9f7c4343f09a8a5c16dc48a12a?p=8bdf3e672ef14514978da0ed7724869c&pm=c)
* Condition on whether top bar renders includes whether the page starts with `/admin` or is `/`
1. Go through different pages
https://user-images.githubusercontent.com/40974372/204729283-6838a2b1-da52-4977-b5cb-75b33381e5b9.mov
* See inline comments
> fix: navbar login states

- frontend/src/APIClients/AdminAPIClient.ts
Impromptu fix. Currently deployment in staging heroku is failing (probably because the code can't be compiled)
* 
1.
*
> Fix: Fixes Bearer Token usage in edit/delete FormQuestion in form template 

- .github/workflows/firebase-hosting-pull-request.yml
- .github/workflows/lint.yml
Re-adding preview links on frontend changes
* These are just fixes, need separate changes for prod deploy
> fix: remove python backend, previews on dev

- .github/workflows/firebase-hosting-pull-request.yml
- Separate credentials for deployment
> Fix: Change pull request credentials to preview

- frontend/src/components/pages/AccessControl/index.tsx
[Access Management: Loading state for the table](https://www.notion.so/uwblueprintexecs/Access-Management-Loading-state-for-the-table-50e1169813f34db99830171c358e3388)
* Added access table loading state
* Added access table empty state
1. go to `/admin/access-control`
*
> feat: add access table loading and empty state

- .github/workflows/firebase-hosting-pull-request.yml
Reverts uwblueprint/focus-on-nature#180
> Revert "Fix: Change pull request credentials to preview"

- backend/typescript/server.ts
> Test Heroku deploy with trivial backend change

- backend/typescript/rest/adminRoutes.ts
- backend/typescript/rest/campRoutes.ts
- backend/typescript/rest/camperRoutes.ts
- backend/typescript/rest/entityRoutes.ts
- backend/typescript/rest/userRoutes.ts
[Refactor: Add authentication to our endpoints](https://www.notion.so/uwblueprintexecs/Refactor-Add-authentication-to-our-endpoints-5930b127a85f472c93d2629360752f41)
* Added `isAuthorizedByRole(new Set(["Admin"]))`, `isAuthorizedByRole(new Set(["CampCoordinator"]))`, or `isAuthorizedByRole(new Set(["Admin", "CampCoordinator"]))` to the middleware functions of express endpoints.
* Any endpoints without any of the above 2 middleware functions are "unprotected" and can be publicly accesses.
1. Refer to [postman link](https://app.getpostman.com/join-team?invite_code=f865ff637c619599c772771953b9ec29) for the testing the api calls. Note that you will have to provide your own `Authorization` variable in environments.
* Focus on any endpoint functions with comment "//ROLES:" above. Any endpoints …
> Edit Endpoint Route Perms

- .github/actions/heroku-deploy/action.yml
> fix: wording to check for rebuild

- backend/typescript/server.ts
> fix: quick backend change to check deploy

- .github/actions/firebase-hosting/action.yml
- .github/workflows/deploy-prod.yml
- frontend/.firebaserc
Multi-site docs: https://firebase.google.com/docs/hosting/multisites
Action used: https://github.com/FirebaseExtended/action-hosting-deploy/blob/277f5a4430001fb24be11d84c0b45ed0c0bb3e92/src/deploy.ts#L138-L148
> fix: prod alias site

- frontend/src/components/common/StepperNavigation/StepperTab.tsx
- frontend/src/components/pages/CampCreation/CampCreationNavStepper.tsx
- frontend/src/components/pages/RegistrantExperience/RegistrationExperienceSteps.ts
- frontend/src/components/pages/RegistrantExperience/RegistrationNavStepper.tsx
- frontend/src/components/pages/RegistrantExperience/Waiver/WaiverReducer.tsx
- frontend/src/components/pages/RegistrantExperience/Waiver/index.tsx
- frontend/src/components/pages/RegistrantExperience/index.tsx
- frontend/src/types/waiverTypes.tsx
title
* Use breakpoints and two components for mobile stepper
* Refactor of logic to support both steppers
* Persist waiver signature once filled out
1. Try responsive design on registrant flow
2. Make sure nothing's broken on camp creation flow
* couldn't figure out how to change size of icon in mobile stepper
https://user-images.githubusercontent.com/40974372/207770928-476ec569-551b-493f-aad6-edc7611a75fd.mov
> Fix: mobile navigation stepper and persist waiver

- frontend/src/components/pages/RegistrantExperience/index.tsx
1. Check URL with/without valid id
* Nothing too exciting, but should unblock us with anything with dealing with the camp state
* Check the loading state (maybe not the cleanest approach)
* Check no visual changes from existing
> Make GET request on registration page

- .github/workflows/deploy-prod.yml
- .github/workflows/firebase-hosting-merge.yml
- .github/workflows/firebase-hosting-pull-request.yml
- frontend/.firebaserc
- frontend/firebase.json
See second prod deploy error messages
- https://medium.com/@luazhizhan/how-to-deploy-multiple-sites-to-firebase-hosting-part-1-a56949876c64
- https://firebase.google.com/docs/cli/targets
- https://firebase.blog/posts/2016/07/deploy-to-multiple-environments-with
> fix: alias not found

- frontend/src/App.tsx
- frontend/src/components/pages/WaitlistExperience/ConfirmationPage.tsx
- frontend/src/components/pages/WaitlistExperience/PersonalInfo/index.tsx
- frontend/src/components/pages/WaitlistExperience/WaitlistFooter.tsx
- frontend/src/components/pages/WaitlistExperience/index.tsx
- frontend/src/constants/Routes.ts
[Registrant Experience: Dummy components + View only Footer](https://www.notion.so/uwblueprintexecs/Task-Board-F22-9e03bf9f7c4343f09a8a5c16dc48a12a?p=1bb8824cfae5423ebbee86b12b6f5e7f&pm=c)
* 
1. go to the waitlist route. No call to backend so camp id doesn't matter right now
*
> Waitlist dummy components and view only footer

- .github/actions/heroku-deploy/action.yml
* https://github.com/uwblueprint/rowan-house/commit/9311720c759a79ac87b8f02dc23c5a6091f9d757
1.
*
> Force push to Heroku backend for deployments

- frontend/src/components/pages/RegistrantExperience/RegistrationFooter.tsx
- frontend/src/components/pages/RegistrantExperience/RegistrationNavStepper.tsx
- frontend/src/components/pages/RegistrantExperience/ReviewRegistration/PaymentSummary.tsx
- frontend/src/components/pages/RegistrantExperience/ReviewRegistration/ReviewInformation.tsx
- frontend/src/components/pages/RegistrantExperience/ReviewRegistration/index.tsx
- frontend/src/components/pages/RegistrantExperience/Waiver/index.tsx
- frontend/src/components/pages/RegistrantExperience/index.tsx
- frontend/src/theme/textStyles.ts
- frontend/src/types/RegistrationTypes.ts
[Registrant Experience: Payment Summary Page](https://www.notion.so/uwblueprintexecs/Registrant-Experience-Payment-Summary-Page-cb1d01aecd384edfa55776b6e188a866)
Also fixes some tablet/mobile styling on the waiver page
1. It's the current page for the "review" step, since nothing else exists there atm. I'm working on some stepper fixes that will make the flow a bit clearer, but the component itself is done 
* Check mobile styling, scrolling behaviour
>  Create payment summary page

- frontend/src/components/common/formQuestions/AddQuestionModal/index.tsx
> fix: edit modal primary button label

- frontend/src/components/common/RequiredAsterisk.tsx
- frontend/src/components/pages/RegistrantExperience/PersonalInfo/CamperCard.tsx
- frontend/src/components/pages/RegistrantExperience/PersonalInfo/ContactCard.tsx
- frontend/src/components/pages/RegistrantExperience/PersonalInfo/index.tsx
- frontend/src/components/pages/RegistrantExperience/PersonalInfo/personalInfoReducer.tsx
- frontend/src/components/pages/RegistrantExperience/RegistrationFooter.tsx
- frontend/src/components/pages/RegistrantExperience/index.tsx
- frontend/src/types/CamperTypes.ts
- frontend/src/types/PersonalInfoTypes.ts
[Registration Form: Personal Info Step view only components & Add/Remove camper ](https://www.notion.so/uwblueprintexecs/Registration-Form-Personal-Info-Step-view-only-components-Add-Remove-camper-6645744f9ff248378376d8da67fbe787)
* Implemented personal info registration state by using `setCampers` useState. I directly edit the `campers` object
* `camperReducer` handles getting callbacks from `PersonalInfo/index.tsx` and handles updating `campers` object
* `checkPersonalInfoFilled` is a helper function for checking that the personal info page is filled correctly
* `usePersonalInfoHook` is a wrapper function to make calling `setCampers` easier. It provides a dispatch function which `camperCard` and `contactCard` use to update state.
1. Check for camper add, update, delete
3.  Check for …
> Personal info registration

- frontend/src/components/common/formQuestions/QuestionsAccordionItem.tsx
[Registration Form: Fixing Scale of Accordion Component](https://www.notion.so/uwblueprintexecs/Registration-Form-Fixing-Scale-of-Accordion-Component-dde9346fb60345748ac8ff7733ae469c)
* 
1. go to `/admin/global-forms`
2. see that the accordion labels are properly sized now
*
> Registration Form: Fixing Scale of Accordion Component

- frontend/src/components/pages/RegistrantExperience/PersonalInfo/CamperCard.tsx
- frontend/src/components/pages/RegistrantExperience/PersonalInfo/personalInfoReducer.tsx
- frontend/src/components/pages/RegistrantExperience/RegistrationFooter.tsx
> Fix: Typo in personal info finished calculation

- frontend/src/components/pages/CampOverview/CampDetails.tsx
[Camp Overview: change URL on camp overview page to new url of session selection page in registration flow](https://www.notion.so/uwblueprintexecs/Task-Board-F22-9e03bf9f7c4343f09a8a5c16dc48a12a?p=b1e91cb6396d4171a0e5cd4107cf5257&pm=c)
* 
1.
*
> fix: Update camp details copy URL

- frontend/src/components/pages/CampOverview/CampersTable/CampersTable.tsx
- frontend/src/components/pages/CampOverview/RemoveCamperModal/ConfirmModal.tsx
- frontend/src/components/pages/CampOverview/RemoveCamperModal/SelectModal.tsx
- frontend/src/components/pages/CampOverview/RemoveCamperModal/index.tsx
- frontend/src/theme/components/Checkbox.ts
- frontend/src/theme/index.ts
[Remove Camper from session broken](https://www.notion.so/uwblueprintexecs/Remove-Camper-from-session-broken-99cd3ecae3114d8b9a67f95b1f60b5db)
* Added custom styling to checkboxes (Previously no checkbox styling was present)
* Fix bug where selected camper doesn't reset after deletion
* Verified deletion of campers
1. 
* 
Previous Error with selected camper:
[React App (3).webm](https://user-images.githubusercontent.com/117593511/209906386-e6f0ca56-ddf5-4459-a71a-0961b3c37b7d.webm)
> Remove camper from session broken

- frontend/src/components/pages/CampOverview/CampersTable/CamperDetailsBadge.tsx
[Camp Overview: Change the EDLP badge on the camper to check for array length instead of array existence](https://www.notion.so/uwblueprintexecs/Camp-Overview-Change-the-EDLP-badge-on-the-camper-to-check-for-array-length-instead-of-array-existe-8994f368a4f54b4692d20968b0a63705)
* 
1.
*
> Camp Overview: Change the EDLP badge on the camper to check for array length instead of array existence

- backend/typescript/rest/camperRoutes.ts
- backend/typescript/services/implementations/camperService.ts
- backend/typescript/services/interfaces/camperService.ts
- backend/typescript/utilities/stripeUtils.ts
On payment success, update db to indicate that camper `hasPaid=true`
* 
1.
*
> [1/n] Create confirm payment endpoint

- backend/typescript/middlewares/validators/camperValidators.ts
- backend/typescript/rest/camperRoutes.ts
- backend/typescript/services/implementations/camperService.ts
- backend/typescript/services/interfaces/camperService.ts
- backend/typescript/types.ts
- backend/typescript/utilities/stripeUtils.ts
> [2/n] Modify registerCamper endpoints with Stripe creation

- backend/typescript/utilities/stripeUtils.ts
* https://stripe.com/docs/payments/checkout/discounts
1. Create a discount with a promo code in https://dashboard.stripe.com/test/coupons
2. Enter promo code at checkout
3. Check that payment goes through properly
*
> Allow coupons on Stripe checkout

- .github/actions/heroku-deploy/action.yml
- .github/workflows/deploy-prod.yml
- .github/workflows/heroku-deploy-dev-ts.yml
> fix: CLIENT_URL env variable undefined in deploys

- backend/typescript/utilities/CampUtils.ts
Trivial change to retrigger backend deploy
> Remove console logs

- backend/typescript/package.json
- backend/typescript/utilities/CampUtils.ts
- backend/typescript/yarn.lock
- frontend/package.json
- frontend/src/components/pages/RegistrantExperience/RegistrationResult/RegistrationInfoCard.tsx
- frontend/src/components/pages/RegistrantExperience/RegistrationResult/index.tsx
- frontend/src/utils/CampUtils.ts
- frontend/src/utils/RegistrationUtils.ts
- frontend/yarn.lock
* Improves handling of EDLP (we need to consider daylight savings for eg., adjust beyond `offset = 5`) using the `date-fns` (already in frontend) and `date-fns-tz` libraries
* Found bug in minutes calculation
* Display non-dummy sessions data on result page
1.
*
> [5/n] Fixes: EDLP logic

- frontend/src/components/pages/RegistrantExperience/RegistrationSteps/AdditionalInfo/QuestionCards/CamperQuestionsCard.tsx
- frontend/src/components/pages/RegistrantExperience/RegistrationSteps/AdditionalInfo/QuestionCards/EarlyDropOffLatePickupCard.tsx
- frontend/src/components/pages/RegistrantExperience/RegistrationSteps/AdditionalInfo/QuestionCards/QuestionsCardWrapper.tsx
- frontend/src/components/pages/RegistrantExperience/RegistrationSteps/AdditionalInfo/additionalInfoReducer.tsx
- frontend/src/components/pages/RegistrantExperience/RegistrationSteps/AdditionalInfo/edlpSessionRegistration.tsx
- frontend/src/components/pages/RegistrantExperience/RegistrationSteps/PersonalInfo/CamperCard.tsx
- frontend/src/components/pages/RegistrantExperience/RegistrationSteps/PersonalInfo/ContactCard.tsx
- frontend/src/components/pages/RegistrantExperience/RegistrationSteps/QuestionGroups/MultipleChoiceGroup.tsx
- frontend/src/components/pages/RegistrantExperience/RegistrationSteps/QuestionGroups/MultiselectGroup.tsx
- frontend/src/components/pages/RegistrantExperience/RegistrationSteps/QuestionGroups/TextInputGroup.tsx
- frontend/src/components/pages/RegistrantExperience/RegistrationSteps/ReviewRegistration/ReviewInformation/EditAdditionalQuestionsCard.tsx
- frontend/src/components/pages/RegistrantExperience/RegistrationSteps/ReviewRegistration/ReviewInformation/EditCamperCard.tsx
- frontend/src/components/pages/RegistrantExperience/RegistrationSteps/ReviewRegistration/ReviewInformation/EditCardFooter.tsx
- frontend/src/components/pages/RegistrantExperience/RegistrationSteps/ReviewRegistration/ReviewInformation/EditCardHeader.tsx
- frontend/src/components/pages/RegistrantExperience/RegistrationSteps/ReviewRegistration/ReviewInformation/EditContactCard.tsx
- frontend/src/components/pages/RegistrantExperience/RegistrationSteps/ReviewRegistration/ReviewInformation/index.tsx
- frontend/src/theme/colors.ts
[Registrant Experience: Review Information Step (Additional Info)](https://www.notion.so/uwblueprintexecs/Registrant-Experience-Review-Information-Step-Additional-Info-d723a8b7740847c7be9ede62c695a60b)
* Added an `EditAdditionalQuestionsCard.tsx` component, very similar to the other edit components in the same folder (editing the camper and contact card)
* Also added an edit header (`EditCardHeader.tsx`) to abstract away some of the common implementations
* Made lots of design updates mostly regarding responsiveness to the additional info step (step 2 of registration), which was needed since my component uses the same styles
1. Run it locally, try to register any camp (i.e. http://localhost:3000/register/camp/63139c7bc3d7b55b44a01531) and ensure that on the review page, everything works …
> Registrant Experience: Review Information Step (Additional Info)

- frontend/src/components/pages/CampCreation/CampDetails/index.tsx
- frontend/src/components/pages/CampCreation/index.tsx
Add states to double check for non-negative, lower < upper, etc.
* 
1.
*
> Fix: camp creation validator logic

- frontend/src/components/pages/CampCreation/ScheduleSessions/SidePanel/ScheduledSessionsCard.tsx
- frontend/src/components/pages/CampOverview/index.tsx
- frontend/src/components/pages/CampsList/CampsTable.tsx
- frontend/src/components/pages/CampsList/PreviewModalSessionRow.tsx
- frontend/src/components/pages/CampsList/index.tsx
- frontend/src/components/pages/RegistrantExperience/RegistrationResult/RegistrationInfoCard.tsx
- frontend/src/components/pages/RegistrantExperience/RegistrationResult/index.tsx
- frontend/src/components/pages/RegistrantExperience/RegistrationSteps/AdditionalInfo/edlpSessionRegistration.tsx
- frontend/src/components/pages/RegistrantExperience/RegistrationSteps/AdditionalInfo/index.tsx
- frontend/src/components/pages/RegistrantExperience/RegistrationSteps/ReviewRegistration/index.tsx
- frontend/src/components/pages/RegistrantExperience/RegistrationSteps/index.tsx
- frontend/src/components/pages/RegistrantExperience/SessionSelection/CampSessionBoard.tsx
- frontend/src/components/pages/RegistrantExperience/SessionSelection/SessionCard.tsx
- frontend/src/components/pages/RegistrantExperience/index.tsx
- frontend/src/types/RegistrationTypes.ts
- frontend/src/utils/CampUtils.ts
- frontend/src/utils/RegistrationUtils.ts
[Registration Form: Hide camp session card from session selection page if the session is finished/in progress](https://www.notion.so/uwblueprintexecs/Task-Board-F22-9e03bf9f7c4343f09a8a5c16dc48a12a?p=8da257cec7db4d0a868a48db1a4ed59c&pm=c)
[Registration Form: Restrict access to session selection page if camp is complete](https://www.notion.so/uwblueprintexecs/Task-Board-F22-9e03bf9f7c4343f09a8a5c16dc48a12a?p=d88c3f1854ca47aea16860bbfc2ef1ed&pm=c)
This PR does a couple things:
- Only show completed sessions as cards in the session selection page (edge case outlined in code comments)
- Add a zero-state for no sessions available for signup
- Fix ordering on camps table, unify ordering for camp sessions date range logic
- Add loading states for camps navigation (if you go between years, …
> fix: session date ordering, hide completed sessions

- frontend/src/components/pages/CampCreation/index.tsx
- frontend/src/components/pages/RegistrantExperience/RegistrationSteps/PersonalInfo/CamperCard.tsx
- frontend/src/components/pages/RegistrantExperience/RegistrationSteps/PersonalInfo/ContactCard.tsx
- frontend/src/components/pages/RegistrantExperience/RegistrationSteps/ReviewRegistration/ReviewInformation/EditCamperCard.tsx
- frontend/src/components/pages/RegistrantExperience/RegistrationSteps/ReviewRegistration/ReviewInformation/EditContactCard.tsx
- frontend/src/components/pages/RegistrantExperience/RegistrationSteps/ReviewRegistration/ReviewInformation/index.tsx
[Registrant Experience: Review Information Step (Add PersonalInfo formResponses to EditCamperCard component)](https://www.notion.so/uwblueprintexecs/Registrant-Experience-Review-Information-Step-Add-PersonalInfo-formResponses-to-EditCamperCard-com-3593ba099bc84886903072b4111c41b3)
* Added personalInfoQuestions and emergencyContactQuestions to the EditCamperCard and EditContactCard components respectively
* Note: These were already in the CamperCard and ContactCard, just had to add them into the editing step.
* Also added the neccesary error validation.
https://user-images.githubusercontent.com/30396273/213904761-d99bd2e6-8149-47d1-b31d-483150427b53.mp4
1. Go to http://localhost:3000/register/camp/63cca95b7f878ceccacb61bc (this has additional personalinfoquestions and emergency contact …
> Registrant Experience: Review Information Step (Add PersonalInfo and EmergencyContactQuestionsto EditCamperCard/ContactCard components)

- frontend/src/components/pages/CampCreation/index.tsx
- frontend/src/components/pages/RegistrantExperience/index.tsx
- frontend/src/components/pages/WaitlistExperience/WaitlistFooter.tsx
[Resolve error when registering for non-existant camp](https://www.notion.so/uwblueprintexecs/Navigate-to-404-page-when-registering-for-non-existant-camp-f6dc0daeff154b4a9f2e0054315d4f6f)
* Added another case of a camp not found.
1. Go to http://localhost:3000/register/camp/thiscampclearlydoesntexist (or any other camp id that doesn't exist) and you should see a message saying "Error: Camp not found. Please go back and try again."
* Functionality
> Resolve error when registering for non-existant camp

- frontend/src/components/pages/RegistrantExperience/RegistrationSteps/AdditionalInfo/QuestionCards/EDLPSelectionControl.tsx
- frontend/src/components/pages/RegistrantExperience/RegistrationSteps/AdditionalInfo/QuestionCards/EarlyDropOffLatePickupCard.tsx
- frontend/src/components/pages/RegistrantExperience/RegistrationSteps/ReviewRegistration/ReviewInformation/EditEDLPCard.tsx
- frontend/src/components/pages/RegistrantExperience/RegistrationSteps/ReviewRegistration/ReviewInformation/index.tsx
- frontend/src/components/pages/RegistrantExperience/RegistrationSteps/ReviewRegistration/index.tsx
- frontend/src/components/pages/RegistrantExperience/RegistrationSteps/index.tsx
[Registrant Experience: Review Information Step (EDLP)](https://www.notion.so/uwblueprintexecs/Registrant-Experience-Review-Information-Step-EDLP-d03c482f5d6343cba3e1118247119357)
* Transferred over the components, making minor changes (often just styling) when needed (explained in the code comments)
1. Try registering for any camp, http://localhost:3000/register/camp/6396319f01dd5e987a03b516 has EDLP enabled but http://localhost:3000/register/camp/6397f94e2ff11dcda0ba4960 doesn't.
2. Proceed to the review step and test the review EDLP component, trying out saving, making changes then cancelling, then confirm that these changes actually persist (navigate back to step 2).
3. If a camp doesn't have EDLP (like the second one I posted above), you should not see the review EDLP accordion at …
> Registrant Experience: Review Information Step (EDLP)

- frontend/src/components/common/formQuestions/AddQuestionModal/index.tsx
[Prevent same option from being created for multiple choice](https://www.notion.so/uwblueprintexecs/Prevent-same-option-from-being-created-for-multiple-choice-51dc19f83b7f426ab007360a0a5b12ff)
* Implemented error handling when options for multiple choice or multi-select are not unique
* Refactored error handling for options to use enum 
1. Navigate to `<baseURL>/admin/add-camp`
2. On the Registration Form page, add a new question
3. Choose multiple choice as Question Type and try Save -> should see error You must enter at least 2 options
4. Choose checkbox as Question Type and try Save -> should see error You must enter at least 1 option
5. Choose multiple choice as Question Type, add a second option, type some value into one of the options and try Save -> should see error Options cannot …
> fix: prevent duplicate multiple choice

- backend/typescript/rest/camperRoutes.ts
- backend/typescript/services/implementations/camperService.ts
- backend/typescript/utilities/stripeUtils.ts
- frontend/src/components/pages/RegistrantExperience/RegistrationResult/index.tsx
- frontend/src/components/pages/RegistrantExperience/SessionSelection/CampSessionBoard.tsx
- frontend/src/components/pages/RegistrantExperience/SessionSelection/SessionCard.tsx
[1/2] https://www.notion.so/uwblueprintexecs/Task-Board-F22-9e03bf9f7c4343f09a8a5c16dc48a12a?p=7f51d5e490d0494ea2512dd2b463186d&pm=c
- Need to fix the camper charges if there was a coupon used
* Right now, we send confirmation email in the "create campers" request, and then confirm payment as a separate request. The confirmation email (as well as sending the waiver eventually) should be sent after payment is completed
* We do have to figure out how to handle incomplete checkouts -- should they continue holding capacity in the camp forever?
* WHEN THIS GETS MERGED TO STAGING: Enable the backend endpoint in the [test Stripe dashboard](https://dashboard.stripe.com/test/webhooks)
* WHEN THIS GETS MERGED TO MAIN: Add the backend endpoint in the production Stripe dashboard to listen to …
> Setup Stripe webhooks

- backend/typescript/services/implementations/camperService.ts
- backend/typescript/services/interfaces/camperService.ts
[Cancellation/Refund: Auto cancel camper registration and send cancellation confirmation email to parent on successful refund](https://www.notion.so/uwblueprintexecs/Cancellation-Refund-Auto-cancel-camper-registration-and-send-cancellation-confirmation-email-to-par-52223aabb0b9464ea6645e4affbe5149?pvs=4)
* Implemented batch processing camper cancellations
* Note this does not have its own Notion ticket as it's part of a larger ticket
Note: deletion currently can't be processed unless payment is actually made through Stripe
1. In Postman, send a DELETE request to http://localhost:3000/campers/cancel-registration, giving `chargeId` as a key and array of `camperId`s (see below for reference)
2. Test that cancellation does not go through if session start date is less than 30 days and waitlist …
> feat: batch process camper cancellations

- frontend/src/components/common/formQuestions/AddQuestionModal/QuestionOptionSection.tsx
- frontend/src/components/common/personalInfoRegistration/personalInfoReducerInterface.ts
- frontend/src/components/pages/CamperRefundCancellation/CamperRefundFooter.tsx
- frontend/src/components/pages/CamperRefundCancellation/CamperRefundInfoCard.tsx
- frontend/src/components/pages/RegistrantExperience/RegistrationSteps/PersonalInfo/personalInfoReducer.tsx
- frontend/src/components/pages/RegistrantExperience/RegistrationSteps/ReviewRegistration/ReviewInformation/EditContactCard.tsx
Literally just `yarn fix`
Not fixing any lint problems that it doesn't automatically fix, I'll bring those up with the PR authors.
> chore: fix frontend lint

- backend/typescript/rest/camperRoutes.ts
- backend/typescript/services/implementations/camperService.ts
- frontend/src/APIClients/CamperAPIClient.ts
- frontend/src/components/pages/CamperRefundCancellation/CamperRefundFooter.tsx
- frontend/src/components/pages/CamperRefundCancellation/CamperRefundInfoCard.tsx
- frontend/src/components/pages/CamperRefundCancellation/index.tsx
- frontend/src/types/CamperTypes.ts
No notion link, was follow up changes from RefundCancellation ticket
* Added functionality where when clicking the request refund button, we will send an HTTP PUT with the DTO to the same endpoint of our GET for refund info
* Added a dummy PUT endpoint that returns an empty array `[]`. I also didn't update the `refunds` state with the response from our PUT endpoint since the endpoint does not exist yet. Thought I'd keep it simple to make it easier to resolve merge conflicts for whoever is working on the actual endpoint
* Added loading state for the button when the API is called
Can't really test... you'll have to add `console.log`'s in certain places to see if the request is going through
* I added an empty dependency array to `index.tsx` in CamperRefundCancellation since I noticed that …
> Derrick catherine/send data on request refund
